import { Platform, StyleSheet } from 'react-native';
const palette = { green: '#179B7D', greenDark: '#075247', greenSoft: '#E8FAF4', amber: '#F7B531', amberSoft: '#FFF3D8', ink: '#1E252B', muted: '#7B858F', border: '#E7EBEF', panel: '#F7F8F6', white: '#FFFFFF', danger: '#EE6B6E' };

export const styles = StyleSheet.create({
  appRoot: {
    flex: 1,
    backgroundColor: palette.panel,
    alignItems: 'center',
  },
  workspace: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingBottom: 18,
  },
  workspaceAdmin: {
    justifyContent: 'flex-start',
    paddingHorizontal: 0,
    paddingBottom: 0,
  },
  phoneStage: {
    flex: 1,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  phoneStageSmall: {
    paddingHorizontal: 0,
  },
  phoneFrame: {
    width: '100%',
    maxWidth: 414,
    height: '100%',
    maxHeight: 896,
    backgroundColor: palette.white,
    overflow: 'hidden',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.border,
    shadowColor: '#0D2A22',
    shadowOpacity: 0.12,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  phoneContent: {
    flex: 1,
    backgroundColor: palette.white,
  },
  screenFull: {
    flex: 1,
    backgroundColor: palette.white,
  },
  screenScrollContent: {
    paddingHorizontal: 16,
    paddingBottom: 120,
  },
  rtlText: {
    writingDirection: 'rtl',
    textAlign: 'right',
    color: palette.ink,
    fontFamily: Platform.select({ android: 'sans-serif', ios: 'Arial', web: 'Arial' }),
  },
  statusBar: {
    height: 48,
    paddingHorizontal: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: palette.white,
  },
  statusTime: {
    fontSize: 16,
    fontWeight: '700',
    color: '#0D2542',
  },
  statusIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  signalBars: {
    height: 16,
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 2,
  },
  signalBar: {
    width: 3,
    borderRadius: 2,
    backgroundColor: '#0D2542',
  },
  wifi: {
    color: '#0D2542',
    fontSize: 18,
    fontWeight: '800',
  },
  battery: {
    width: 24,
    height: 12,
    borderRadius: 3,
    borderWidth: 1.6,
    borderColor: '#0D2542',
    padding: 2,
  },
  batteryFill: {
    flex: 1,
    borderRadius: 2,
    backgroundColor: '#0D2542',
  },
  header: {
    minHeight: 58,
    paddingTop: 6,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  headerCompact: {
    paddingTop: 0,
  },
  headerActions: {
    flexDirection: 'row',
    gap: 10,
  },
  roundIconGhost: {
    width: 34,
    height: 34,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 17,
    backgroundColor: palette.white,
  },
  headerTitle: {
    fontSize: 14,
    fontWeight: '700',
    minWidth: 72,
  },
  searchWrap: {
    flex: 1,
    minWidth: 0,
    height: 40,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 24,
    backgroundColor: '#F3F4F5',
    paddingHorizontal: 5,
  },
  searchButton: {
    width: 34,
    height: 34,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.green,
  },
  searchInput: {
    flex: 1,
    paddingHorizontal: 10,
    fontSize: 12,
    color: palette.ink,
    writingDirection: 'rtl',
  },
  promoBanner: {
    height: 126,
    marginTop: 12,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: palette.green,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    paddingHorizontal: 14,
  },
  promoText: {
    flex: 1,
    alignItems: 'flex-end',
  },
  promoTitle: {
    color: palette.white,
    fontSize: 18,
    fontWeight: '900',
  },
  promoBody: {
    color: '#E7FFF7',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 4,
  },
  promoButton: {
    marginTop: 10,
    height: 30,
    paddingHorizontal: 12,
    borderRadius: 16,
    backgroundColor: palette.white,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  promoButtonText: {
    fontSize: 12,
    fontWeight: '800',
    color: palette.greenDark,
  },
  promoImage: {
    width: 118,
    height: 96,
    borderRadius: 8,
    resizeMode: 'cover',
    marginRight: 10,
  },
  categoryStrip: {
    marginTop: 16,
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    gap: 8,
  },
  categoryStripDouble: {
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    rowGap: 12,
  },
  categoryItem: {
    width: 56,
    alignItems: 'center',
  },
  categoryImageWrap: {
    width: 50,
    height: 50,
    borderRadius: 25,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F1F3F4',
  },
  categoryImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  categoryLabel: {
    marginTop: 6,
    fontSize: 11,
    color: palette.ink,
    textAlign: 'center',
  },
  sectionTitle: {
    marginTop: 20,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionName: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  sectionHeading: {
    fontSize: 17,
    fontWeight: '900',
  },
  sectionAction: {
    fontSize: 12,
    fontWeight: '700',
    color: palette.green,
  },
  horizontalCards: {
    flexDirection: 'row-reverse',
    gap: 12,
    paddingHorizontal: 2,
    paddingBottom: 4,
  },
  reelCard: {
    width: 112,
    height: 150,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#111',
  },
  reelThumb: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  reelPlay: {
    position: 'absolute',
    top: 8,
    left: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  reelCount: {
    color: palette.white,
    fontSize: 10,
    fontWeight: '800',
  },
  reelMeta: {
    position: 'absolute',
    bottom: 8,
    right: 8,
    left: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
  },
  miniCart: {
    width: 28,
    height: 28,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.white,
  },
  reelTitle: {
    flex: 1,
    color: palette.white,
    fontSize: 11,
    fontWeight: '800',
  },
  couponCard: {
    width: 132,
    height: 96,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  ticketCutLeft: {
    position: 'absolute',
    left: -8,
    top: 34,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: palette.white,
  },
  ticketCutRight: {
    position: 'absolute',
    right: -8,
    top: 34,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: palette.white,
  },
  couponPrice: {
    color: palette.white,
    fontSize: 16,
    fontWeight: '900',
  },
  couponCode: {
    marginTop: 4,
    color: '#E8FFF7',
    fontSize: 10,
    fontWeight: '700',
  },
  copyButton: {
    marginTop: 8,
    width: 74,
    height: 24,
    borderRadius: 12,
    backgroundColor: palette.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  copyButtonText: {
    color: palette.greenDark,
    fontSize: 11,
    fontWeight: '800',
    textAlign: 'center',
  },
  couponIndex: {
    position: 'absolute',
    bottom: 6,
    left: 8,
    color: '#FFFFFF80',
    fontSize: 10,
  },
  productGrid: {
    marginTop: 12,
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 14,
  },
  productCard: {
    width: '48%',
    backgroundColor: palette.white,
    borderRadius: 8,
    padding: 7,
    borderWidth: 1,
    borderColor: palette.border,
    shadowColor: '#0F211C',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  productCardCompact: {
    width: 158,
  },
  productImageBox: {
    height: 132,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#F2F3F2',
  },
  productImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  heartButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#00000055',
  },
  productBadges: {
    position: 'absolute',
    left: 7,
    bottom: 7,
    right: 7,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  ratingPill: {
    height: 22,
    paddingHorizontal: 7,
    borderRadius: 11,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: '#00000066',
  },
  ratingText: {
    color: palette.white,
    fontSize: 10,
    fontWeight: '800',
  },
  deliveryPill: {
    height: 22,
    paddingHorizontal: 7,
    borderRadius: 11,
    justifyContent: 'center',
    backgroundColor: '#00000066',
  },
  deliveryText: {
    color: palette.white,
    fontSize: 9,
    fontWeight: '700',
  },
  productTitle: {
    marginTop: 8,
    minHeight: 38,
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '900',
  },
  storeLine: {
    marginTop: 2,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 5,
  },
  storeAvatar: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#CBD3D8',
  },
  storeName: {
    flex: 1,
    color: palette.muted,
    fontSize: 10,
  },
  productPrice: {
    marginTop: 7,
    fontSize: 16,
    color: palette.green,
    fontWeight: '900',
  },
  productCart: {
    marginTop: 6,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.greenSoft,
  },
  detailsContent: {
    paddingBottom: 120,
    backgroundColor: palette.white,
  },
  detailsTopBar: {
    height: 54,
    paddingHorizontal: 16,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  detailsTopButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.greenSoft,
  },
  detailsHeaderTitle: {
    fontSize: 16,
    fontWeight: '900',
    textAlign: 'center',
  },
  detailsImageWrap: {
    height: 330,
    marginHorizontal: 16,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#F0F2F2',
  },
  detailsImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  detailsFavorite: {
    position: 'absolute',
    top: 14,
    right: 14,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#00000055',
  },
  detailsDots: {
    position: 'absolute',
    bottom: 14,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 6,
  },
  detailsDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#FFFFFF99',
  },
  detailsDotActive: {
    width: 20,
    height: 7,
    borderRadius: 4,
    backgroundColor: palette.white,
  },
  detailsBody: {
    padding: 16,
  },
  detailsBadgeRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  detailsDelivery: {
    height: 30,
    paddingHorizontal: 10,
    borderRadius: 15,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 5,
    backgroundColor: palette.greenSoft,
  },
  detailsDeliveryText: {
    color: palette.green,
    fontSize: 11,
    fontWeight: '800',
  },
  detailsRating: {
    height: 30,
    paddingHorizontal: 10,
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: palette.amberSoft,
  },
  detailsRatingText: {
    fontSize: 12,
    fontWeight: '900',
  },
  detailsTitle: {
    alignSelf: 'stretch',
    marginTop: 14,
    fontSize: 21,
    lineHeight: 29,
    fontWeight: '900',
  },
  detailsStoreRow: {
    marginTop: 14,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 10,
  },
  detailsStoreAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#D8DDDF',
  },
  detailsStoreName: {
    fontSize: 13,
    fontWeight: '900',
  },
  detailsStoreButton: {
    height: 32,
    paddingHorizontal: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.green,
    justifyContent: 'center',
  },
  detailsStoreButtonText: {
    color: palette.green,
    fontSize: 11,
    fontWeight: '900',
    textAlign: 'center',
  },
  detailsPrice: {
    marginTop: 18,
    color: palette.green,
    fontSize: 25,
    fontWeight: '900',
  },
  detailsDivider: {
    height: 1,
    marginVertical: 18,
    backgroundColor: palette.border,
  },
  detailsSectionTitle: {
    fontSize: 15,
    fontWeight: '900',
  },
  detailsDescription: {
    alignSelf: 'stretch',
    marginTop: 8,
    color: palette.muted,
    fontSize: 13,
    lineHeight: 22,
  },
  detailsQuantityRow: {
    marginTop: 22,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  detailsQuantity: {
    height: 38,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  detailsQtyButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.greenSoft,
  },
  detailsQtyValue: {
    minWidth: 22,
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  detailsAddButton: {
    marginTop: 24,
    height: 60,
    borderRadius: 8,
    paddingHorizontal: 20,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: palette.green,
  },
  detailsAddText: {
    color: palette.white,
    fontSize: 16,
    fontWeight: '900',
  },
  detailsAddSub: {
    marginTop: 2,
    color: '#DFFFF5',
    fontSize: 11,
  },
  emptyCart: {
    flex: 1,
    paddingHorizontal: 30,
    paddingBottom: 90,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyCartIcon: {
    width: 88,
    height: 88,
    borderRadius: 44,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.greenSoft,
  },
  emptyCartTitle: {
    marginTop: 18,
    fontSize: 22,
    fontWeight: '900',
    textAlign: 'center',
  },
  emptyCartText: {
    marginTop: 8,
    color: palette.muted,
    fontSize: 13,
    textAlign: 'center',
  },
  emptyCartButton: {
    marginTop: 22,
    height: 46,
    paddingHorizontal: 30,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.green,
  },
  emptyCartButtonText: {
    color: palette.white,
    fontWeight: '900',
    textAlign: 'center',
  },
  cartContent: {
    padding: 16,
    paddingBottom: 120,
  },
  cartHeader: {
    marginBottom: 14,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cartTitle: {
    fontSize: 22,
    fontWeight: '900',
  },
  cartCount: {
    color: palette.muted,
    fontSize: 12,
  },
  cartItem: {
    minHeight: 148,
    marginBottom: 12,
    padding: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.border,
    flexDirection: 'row-reverse',
    gap: 12,
    backgroundColor: palette.white,
  },
  cartItemImage: {
    width: 112,
    height: 126,
    borderRadius: 8,
    resizeMode: 'cover',
  },
  cartItemBody: {
    flex: 1,
    alignItems: 'flex-end',
  },
  cartItemTitle: {
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '900',
  },
  cartItemStore: {
    marginTop: 4,
    color: palette.muted,
    fontSize: 10,
  },
  cartItemPrice: {
    marginTop: 10,
    color: palette.green,
    fontSize: 16,
    fontWeight: '900',
  },
  cartItemFooter: {
    width: '100%',
    marginTop: 'auto',
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cartQty: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 9,
  },
  cartQtyButton: {
    width: 27,
    height: 27,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.greenSoft,
  },
  cartQtyValue: {
    minWidth: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  cartRemove: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 4,
  },
  cartRemoveText: {
    color: palette.danger,
    fontSize: 11,
    fontWeight: '800',
  },
  cartSummary: {
    marginTop: 8,
    padding: 16,
    borderRadius: 8,
    backgroundColor: '#F6F8F7',
  },
  cartSummaryTitle: {
    marginBottom: 14,
    fontSize: 16,
    fontWeight: '900',
  },
  cartSummaryLine: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cartSummaryLabel: {
    color: palette.muted,
    fontSize: 13,
  },
  cartSummaryValue: {
    fontSize: 13,
    fontWeight: '800',
  },
  cartSummaryFree: {
    color: palette.green,
    fontSize: 13,
    fontWeight: '900',
  },
  cartSummaryDivider: {
    height: 1,
    marginVertical: 14,
    backgroundColor: palette.border,
  },
  cartTotalLabel: {
    fontSize: 15,
    fontWeight: '900',
  },
  cartTotalValue: {
    color: palette.green,
    fontSize: 19,
    fontWeight: '900',
  },
  checkoutButton: {
    marginTop: 20,
    height: 50,
    borderRadius: 8,
    paddingHorizontal: 18,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: palette.green,
  },
  checkoutText: {
    color: palette.white,
    fontSize: 15,
    fontWeight: '900',
    textAlign: 'center',
  },
  checkoutContent: {
    paddingHorizontal: 16,
    paddingBottom: 120,
  },
  detailsTopSpacer: {
    width: 36,
    height: 36,
  },
  checkoutSectionTitle: {
    alignSelf: 'stretch',
    marginTop: 14,
    marginBottom: 10,
    fontSize: 16,
    fontWeight: '900',
  },
  checkoutPanel: {
    padding: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.white,
  },
  paymentOptions: {
    gap: 10,
  },
  paymentOption: {
    minHeight: 72,
    padding: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.border,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 12,
    backgroundColor: palette.white,
  },
  paymentOptionActive: {
    borderColor: palette.green,
    backgroundColor: palette.greenSoft,
  },
  paymentRadio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#B8C0C5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  paymentRadioActive: {
    borderColor: palette.green,
  },
  paymentRadioDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: palette.green,
  },
  paymentTitle: {
    fontSize: 13,
    fontWeight: '900',
  },
  checkoutSummary: {
    marginTop: 20,
    marginBottom: 8,
    padding: 16,
    borderRadius: 8,
    backgroundColor: '#F6F8F7',
  },
  successScreen: {
    flex: 1,
    paddingHorizontal: 28,
    paddingBottom: 90,
    alignItems: 'center',
    justifyContent: 'center',
  },
  successIcon: {
    width: 96,
    height: 96,
    borderRadius: 48,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.green,
  },
  successTitle: {
    marginTop: 22,
    fontSize: 24,
    fontWeight: '900',
    textAlign: 'center',
  },
  successText: {
    maxWidth: 300,
    marginTop: 9,
    color: palette.muted,
    fontSize: 13,
    lineHeight: 21,
    textAlign: 'center',
  },
  successOrderNumber: {
    width: '100%',
    marginTop: 24,
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
    backgroundColor: palette.greenSoft,
  },
  successNumber: {
    marginTop: 5,
    color: palette.greenDark,
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  successButton: {
    marginTop: 24,
    height: 48,
    paddingHorizontal: 28,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.green,
  },
  successButtonText: {
    color: palette.white,
    fontSize: 14,
    fontWeight: '900',
    textAlign: 'center',
  },
  offerBand: {
    marginTop: 18,
    flexDirection: 'row-reverse',
    gap: 10,
  },
  offerCard: {
    flex: 1,
    height: 94,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#BFEFE2',
    backgroundColor: palette.greenSoft,
    flexDirection: 'row',
    overflow: 'hidden',
  },
  offerCardAmber: {
    backgroundColor: palette.amberSoft,
    borderColor: '#F8DE9D',
  },
  offerImage: {
    width: 62,
    height: '100%',
    resizeMode: 'cover',
  },
  offerText: {
    flex: 1,
    padding: 9,
    alignItems: 'flex-end',
  },
  offerTitle: {
    color: palette.green,
    fontWeight: '900',
    fontSize: 13,
  },
  offerSub: {
    marginTop: 2,
    color: palette.muted,
    fontSize: 9,
  },
  offerButton: {
    marginTop: 8,
    height: 24,
    paddingHorizontal: 10,
    borderRadius: 12,
    backgroundColor: palette.green,
    justifyContent: 'center',
  },
  offerButtonAmber: {
    backgroundColor: palette.amber,
  },
  offerButtonText: {
    color: palette.white,
    fontSize: 10,
    fontWeight: '800',
  },
  tabs: {
    flexDirection: 'row-reverse',
    gap: 12,
    paddingTop: 14,
    paddingBottom: 8,
  },
  tabsCompact: {
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 8,
  },
  tabItem: {
    minHeight: 34,
    justifyContent: 'center',
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  tabItemActive: {
    borderBottomColor: palette.ink,
  },
  tabText: {
    color: palette.muted,
    fontSize: 14,
    fontWeight: '700',
  },
  tabTextActive: {
    color: palette.ink,
    fontSize: 17,
    fontWeight: '900',
  },
  storeInner: {
    paddingHorizontal: 16,
    paddingBottom: 120,
  },
  storeTopActions: {
    marginTop: 8,
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  storeScreenTitle: {
    flex: 1,
    textAlign: 'center',
    fontWeight: '800',
  },
  greenTiny: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: palette.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  storeHero: {
    width: '100%',
    height: 108,
    borderRadius: 8,
    resizeMode: 'cover',
  },
  storeStats: {
    marginTop: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.border,
    flexDirection: 'row-reverse',
    overflow: 'hidden',
  },
  metric: {
    flex: 1,
    minHeight: 76,
    alignItems: 'center',
    justifyContent: 'center',
    borderLeftWidth: 1,
    borderLeftColor: palette.border,
  },
  metricLabel: {
    marginTop: 5,
    color: palette.muted,
    fontSize: 9,
    textAlign: 'center',
  },
  metricValue: {
    marginTop: 3,
    fontSize: 10,
    fontWeight: '800',
    textAlign: 'center',
  },
  storeRatingCard: {
    marginTop: 18,
    padding: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.border,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 16,
  },
  ratingScoreBox: {
    width: 82,
    alignItems: 'center',
  },
  bigRating: {
    fontSize: 36,
    fontWeight: '900',
  },
  starsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  tinyMuted: {
    color: palette.muted,
    fontSize: 11,
  },
  ratingBars: {
    flex: 1,
    gap: 7,
  },
  ratingBarLine: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
  },
  ratingLabel: {
    width: 42,
    color: palette.muted,
    fontSize: 10,
  },
  ratingTrack: {
    flex: 1,
    height: 6,
    borderRadius: 4,
    backgroundColor: '#EDF0F1',
    overflow: 'hidden',
  },
  ratingFill: {
    height: '100%',
    borderRadius: 4,
    backgroundColor: palette.green,
  },
  storeCardGrid: {
    marginTop: 12,
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 14,
  },
  storeMiniCard: {
    width: '48%',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 8,
  },
  storeMiniImage: {
    width: '100%',
    height: 82,
    borderRadius: 8,
    resizeMode: 'cover',
  },
  storeMiniTitle: {
    marginTop: 7,
    fontWeight: '900',
    fontSize: 13,
  },
  storeMiniSub: {
    color: palette.muted,
    fontSize: 10,
  },
  storeMiniRating: {
    marginTop: 4,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 3,
  },
  storeMiniRatingText: {
    fontSize: 10,
    color: palette.muted,
  },
  visitButton: {
    marginTop: 8,
    height: 30,
    borderRadius: 15,
    backgroundColor: palette.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  visitText: {
    color: palette.white,
    fontSize: 11,
    fontWeight: '800',
    textAlign: 'center',
  },
  rateButton: {
    flex: 1,
    height: 42,
    borderRadius: 21,
    backgroundColor: palette.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rateButtonText: {
    color: palette.white,
    fontWeight: '900',
    textAlign: 'center',
  },
  commentHeader: {
    marginTop: 16,
    marginBottom: 6,
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  commentCard: {
    minHeight: 92,
    marginTop: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 12,
    flexDirection: 'row-reverse',
    gap: 10,
    alignItems: 'center',
  },
  commentAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#E7EAED',
    alignItems: 'center',
    justifyContent: 'center',
  },
  commentContent: {
    flex: 1,
    alignItems: 'flex-end',
  },
  commentName: {
    fontWeight: '900',
  },
  commentText: {
    marginTop: 6,
    fontSize: 12,
    color: palette.ink,
  },
  commentDate: {
    alignSelf: 'flex-start',
    color: palette.muted,
    fontSize: 10,
  },
  rateScreen: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  reviewStoreHeader: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 12,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
  },
  storeAvatarLarge: {
    width: 76,
    height: 76,
    borderRadius: 8,
    backgroundColor: '#F0F1F2',
  },
  reviewStoreName: {
    fontSize: 17,
    fontWeight: '900',
  },
  categoryChipText: {
    alignSelf: 'flex-end',
    marginTop: 5,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 12,
    backgroundColor: palette.greenSoft,
    color: palette.green,
    fontSize: 10,
    fontWeight: '800',
  },
  locationLine: {
    marginTop: 8,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 4,
  },
  rateQuestion: {
    marginTop: 24,
    fontSize: 15,
    fontWeight: '800',
    textAlign: 'center',
  },
  rateStars: {
    marginTop: 14,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 12,
  },
  rateWord: {
    marginTop: 8,
    color: palette.green,
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
  },
  commentBox: {
    marginTop: 16,
    minHeight: 92,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 14,
    color: palette.ink,
    textAlignVertical: 'top',
  },
  uploadRow: {
    marginTop: 14,
    flexDirection: 'row-reverse',
    gap: 10,
  },
  uploadBox: {
    flex: 1,
    height: 86,
    borderRadius: 8,
    backgroundColor: '#F0F1F1',
  },
  uploadDashed: {
    flex: 1,
    height: 86,
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#AAB3BA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadText: {
    marginTop: 6,
    color: palette.muted,
    fontSize: 11,
    textAlign: 'center',
  },
  submitButton: {
    marginTop: 'auto',
    marginBottom: 24,
    height: 50,
    borderRadius: 8,
    backgroundColor: palette.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitText: {
    color: palette.white,
    fontSize: 16,
    fontWeight: '900',
    textAlign: 'center',
  },
  reelsScreen: {
    flex: 1,
    minHeight: 760,
    backgroundColor: '#051B20',
  },
  reelsBackground: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  reelsOverlay: {
    flex: 1,
    justifyContent: 'space-between',
    paddingTop: 18,
    paddingBottom: 18,
  },
  reelsTopButtons: {
    paddingHorizontal: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  reelsLeftButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  reelsButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: palette.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reelsCartSheet: {
    marginHorizontal: 16,
    padding: 16,
    borderRadius: 8,
    backgroundColor: palette.white,
  },
  qtyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sheetPrice: {
    color: palette.green,
    fontSize: 18,
    fontWeight: '900',
  },
  qtyControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  qtyButton: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: palette.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  qtyValue: {
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  qtyLabel: {
    fontSize: 12,
    color: palette.ink,
  },
  addToCartButton: {
    marginTop: 16,
    height: 48,
    borderRadius: 24,
    backgroundColor: palette.green,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  addToCartText: {
    color: palette.white,
    fontSize: 14,
    fontWeight: '900',
    textAlign: 'center',
  },
  authTabs: {
    marginTop: 18,
    alignSelf: 'center',
    flexDirection: 'row-reverse',
    borderRadius: 20,
    backgroundColor: '#F2F4F4',
    padding: 4,
  },
  authTab: {
    height: 32,
    paddingHorizontal: 14,
    borderRadius: 16,
    justifyContent: 'center',
  },
  authTabActive: {
    backgroundColor: palette.green,
  },
  authTabText: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
  },
  authTabTextActive: {
    color: palette.white,
  },
  authTitle: {
    marginTop: 36,
    marginBottom: 24,
    textAlign: 'center',
    fontSize: 22,
    fontWeight: '900',
  },
  authFieldBlock: {
    flex: 1,
    marginBottom: 14,
  },
  authLabel: {
    marginBottom: 8,
    fontSize: 13,
    fontWeight: '700',
  },
  authInputShell: {
    height: 52,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.border,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 14,
  },
  authInput: {
    flex: 1,
    color: palette.ink,
    writingDirection: 'rtl',
  },
  twoColumns: {
    flexDirection: 'row-reverse',
    gap: 12,
  },
  authInline: {
    marginBottom: 22,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  rememberRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 5,
  },
  checkbox: {
    width: 12,
    height: 12,
    borderRadius: 2,
    borderWidth: 1.5,
    borderColor: palette.green,
  },
  linkText: {
    color: palette.green,
    fontWeight: '800',
    fontSize: 12,
    textDecorationLine: 'underline',
  },
  authPrimary: {
    height: 52,
    borderRadius: 8,
    backgroundColor: palette.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  authPrimaryText: {
    color: palette.white,
    fontSize: 17,
    fontWeight: '900',
    textAlign: 'center',
  },
  authQuestion: {
    marginTop: 18,
    color: palette.ink,
    textAlign: 'center',
    fontSize: 13,
  },
  authQuestionRow: {
    marginTop: 14,
    flexDirection: 'row-reverse',
    justifyContent: 'center',
    gap: 6,
  },
  termsRow: {
    marginBottom: 16,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
  },
  dividerRow: {
    marginVertical: 24,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  divider: {
    flex: 1,
    height: 1,
    backgroundColor: palette.border,
  },
  googleButton: {
    height: 54,
    borderRadius: 8,
    backgroundColor: '#F2F2F2',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  googleIcon: {
    width: 24,
    height: 24,
    borderRadius: 12,
  },
  googleText: {
    fontSize: 14,
    color: palette.ink,
    textAlign: 'center',
  },
  bottomNav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 82,
    backgroundColor: palette.white,
    borderTopWidth: 1,
    borderTopColor: palette.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: 12,
    paddingBottom: 10,
  },
  bottomItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 0,
  },
  bottomCenter: {
    transform: [{ translateY: -16 }],
  },
  navIconWrap: {
    height: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cartBadge: {
    position: 'absolute',
    top: -8,
    right: -11,
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.amber,
    borderWidth: 2,
    borderColor: palette.white,
  },
  cartBadgeText: {
    color: palette.white,
    fontSize: 9,
    fontWeight: '900',
    textAlign: 'center',
  },
  navIconActive: {},
  centerButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: palette.white,
    borderWidth: 8,
    borderColor: '#E5F8F2',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0F211C',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  bottomLabel: {
    marginTop: 4,
    color: palette.muted,
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
  },
  bottomLabelActive: {
    color: palette.ink,
    fontWeight: '900',
  },
  toast: {
    position: 'absolute',
    left: 44,
    right: 44,
    bottom: 92,
    minHeight: 44,
    paddingHorizontal: 16,
    borderRadius: 22,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: palette.greenDark,
    shadowColor: '#071E18',
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
    zIndex: 20,
  },
  toastText: {
    color: palette.white,
    fontSize: 12,
    fontWeight: '900',
    textAlign: 'center',
  },
  modeSwitch: {
    marginTop: 12,
    marginBottom: 10,
    height: 42,
    borderRadius: 22,
    padding: 4,
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: palette.border,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 4,
  },
  modeButton: {
    height: 34,
    paddingHorizontal: 14,
    borderRadius: 18,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
  },
  modeButtonActive: {
    backgroundColor: palette.green,
  },
  modeButtonText: {
    color: palette.green,
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
  },
  modeButtonTextActive: {
    color: palette.white,
  },
  adminShell: {
    flex: 1,
    width: '100%',
    flexDirection: 'row-reverse',
    backgroundColor: '#F2F3F1',
  },
  adminShellCompact: {
    flexDirection: 'column',
  },
  adminSidebar: {
    width: 238,
    backgroundColor: palette.greenDark,
    paddingVertical: 26,
    paddingHorizontal: 16,
  },
  adminLogo: {
    color: palette.white,
    fontSize: 26,
    fontWeight: '900',
    textAlign: 'center',
    marginBottom: 28,
  },
  sidebarItem: {
    height: 42,
    borderRadius: 8,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    paddingHorizontal: 12,
    gap: 10,
    marginBottom: 8,
  },
  sidebarItemActive: {
    backgroundColor: '#FFFFFF24',
  },
  sidebarText: {
    color: palette.white,
    fontSize: 13,
    fontWeight: '700',
  },
  supportLine: {
    marginTop: 'auto',
    borderTopWidth: 1,
    borderTopColor: '#FFFFFF24',
    paddingTop: 18,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 10,
  },
  adminChipNav: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row-reverse',
    gap: 8,
    backgroundColor: palette.white,
  },
  adminChip: {
    height: 34,
    borderRadius: 18,
    paddingHorizontal: 12,
    backgroundColor: '#EDF1F0',
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
  },
  adminChipActive: {
    backgroundColor: palette.green,
  },
  adminChipText: {
    fontSize: 12,
    color: palette.greenDark,
    fontWeight: '800',
  },
  adminChipTextActive: {
    color: palette.white,
  },
  adminMain: {
    flex: 1,
  },
  adminTopBar: {
    height: 74,
    paddingHorizontal: 24,
    backgroundColor: palette.white,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 16,
  },
  adminTopBarCompact: {
    paddingHorizontal: 12,
    gap: 8,
  },
  adminUser: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 10,
  },
  adminAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#C8D2D6',
  },
  adminUserName: {
    fontSize: 13,
    fontWeight: '900',
  },
  adminSearch: {
    flex: 1,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#F2F4F4',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    gap: 8,
  },
  adminSearchInput: {
    flex: 1,
    color: palette.ink,
    writingDirection: 'rtl',
    fontSize: 13,
  },
  adminNotify: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.greenSoft,
  },
  adminContent: {
    padding: 24,
    paddingBottom: 40,
  },
  statsGrid: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: 14,
  },
  statCard: {
    flexGrow: 1,
    flexBasis: 180,
    minHeight: 108,
    borderRadius: 8,
    padding: 16,
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: palette.border,
  },
  statIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'flex-end',
  },
  statValue: {
    marginTop: 8,
    fontSize: 22,
    fontWeight: '900',
  },
  statLabel: {
    marginTop: 2,
    color: palette.muted,
    fontSize: 12,
  },
  statDelta: {
    position: 'absolute',
    left: 16,
    bottom: 16,
    fontWeight: '900',
    fontSize: 13,
  },
  adminCardsRow: {
    marginTop: 18,
    flexDirection: 'row-reverse',
    gap: 14,
  },
  adminCardsColumn: {
    flexDirection: 'column',
  },
  ordersMini: {
    flex: 1,
    minWidth: 260,
    borderRadius: 8,
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 16,
  },
  miniOrder: {
    marginTop: 12,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 10,
  },
  miniOrderImg: {
    width: 44,
    height: 44,
    borderRadius: 8,
    resizeMode: 'cover',
  },
  chartCard: {
    flex: 1.5,
    minWidth: 300,
    borderRadius: 8,
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 16,
  },
  cardHeader: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  adminCardTitle: {
    fontSize: 15,
    fontWeight: '900',
  },
  adminCardValue: {
    color: palette.green,
    fontWeight: '900',
  },
  chartArea: {
    height: 150,
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
  },
  chartColumn: {
    width: 22,
    alignItems: 'center',
    justifyContent: 'flex-end',
    flexDirection: 'row',
    gap: 3,
  },
  chartBar: {
    width: 8,
    borderRadius: 4,
    backgroundColor: palette.green,
  },
  chartBarSoft: {
    width: 8,
    borderRadius: 4,
    backgroundColor: '#BFE9DF',
  },
  performanceCard: {
    width: 240,
    borderRadius: 8,
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 16,
    alignItems: 'center',
  },
  donutWrap: {
    marginTop: 12,
    alignItems: 'center',
  },
  donutOuter: {
    width: 92,
    height: 92,
    borderRadius: 46,
    borderWidth: 12,
    borderColor: palette.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  donutInner: {
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.white,
  },
  donutPercent: {
    color: palette.green,
    fontWeight: '900',
  },
  secondaryButton: {
    marginTop: 12,
    height: 34,
    paddingHorizontal: 14,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: palette.border,
    justifyContent: 'center',
  },
  secondaryButtonText: {
    color: palette.green,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
  },
  adminSectionTitle: {
    marginTop: 24,
    marginBottom: 12,
    fontSize: 17,
    fontWeight: '900',
  },
  adminProductGrid: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: 14,
  },
  adminProductCard: {
    flexBasis: 170,
    flexGrow: 1,
    maxWidth: 230,
    borderRadius: 8,
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: palette.border,
    overflow: 'hidden',
  },
  adminProductImage: {
    height: 120,
    width: '100%',
    resizeMode: 'cover',
  },
  adminProductMeta: {
    padding: 10,
    alignItems: 'flex-end',
  },
  adminProductTitle: {
    fontSize: 13,
    fontWeight: '900',
  },
  tableCard: {
    marginTop: 18,
    borderRadius: 8,
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 16,
  },
  tableTools: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  adminPrimary: {
    height: 36,
    borderRadius: 18,
    paddingHorizontal: 14,
    backgroundColor: palette.green,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
  },
  adminPrimaryText: {
    color: palette.white,
    fontWeight: '900',
    fontSize: 12,
  },
  filterButton: {
    height: 36,
    borderRadius: 18,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: palette.border,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
  },
  filterText: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: '800',
  },
  table: {
    minWidth: 760,
  },
  tableHeader: {
    height: 42,
    borderRadius: 8,
    backgroundColor: '#F4F6F6',
    flexDirection: 'row-reverse',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  tableHeaderText: {
    flex: 1,
    color: palette.muted,
    fontSize: 12,
    fontWeight: '900',
  },
  tableRow: {
    minHeight: 62,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
  },
  tableEntity: {
    flex: 1,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
  },
  tableThumb: {
    width: 36,
    height: 36,
    borderRadius: 8,
    resizeMode: 'cover',
  },
  tableName: {
    fontSize: 12,
    color: palette.ink,
  },
});
