import { Platform, StyleSheet } from 'react-native';
const palette = { green: '#179B7D', greenDark: '#075247', greenSoft: '#E8FAF4', amber: '#F7B531', amberSoft: '#FFF3D8', ink: '#1E252B', muted: '#7B858F', border: '#E7EBEF', panel: '#F7F8F6', white: '#FFFFFF', danger: '#EE6B6E' };
const fontFamily = Platform.select({ web: 'Cairo', default: 'Cairo_400Regular' });

export const styles = StyleSheet.create({
  appRoot: {
    flex: 1,
    backgroundColor: palette.panel,
    alignItems: 'stretch',
  },
  workspace: {
    flex: 1,
    width: '100%',
    alignItems: 'stretch',
    justifyContent: 'flex-start',
    paddingHorizontal: 0,
    paddingBottom: 0,
  },
  workspaceAdmin: {
    justifyContent: 'flex-start',
    paddingHorizontal: 0,
    paddingBottom: 0,
  },
  phoneStage: {
    flex: 1,
    width: '100%',
    alignItems: 'stretch',
    justifyContent: 'flex-start',
  },
  phoneStageSmall: {
    paddingHorizontal: 0,
  },
  phoneFrame: {
    flex: 1,
    width: '100%',
    height: '100%',
    backgroundColor: palette.white,
    overflow: 'hidden',
    borderRadius: 0,
    borderWidth: 0,
    shadowOpacity: 0,
    elevation: 0,
  },
  phoneContent: {
    flex: 1,
    backgroundColor: palette.white,
  },
  screenFull: {
    flex: 1,
    backgroundColor: palette.white,
  },
  screenScrollContent: {
    paddingHorizontal: 16,
    paddingTop: 10,
    paddingBottom: 120,
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
  },
  onboardingScreen: {
    flex: 1,
    backgroundColor: palette.white,
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 16,
  },
  onboardingTop: {
    minHeight: 44,
    alignItems: 'flex-start',
    justifyContent: 'center',
  },
  guestLink: {
    minHeight: 36,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
  },
  guestLinkText: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: '500',
  },
  onboardingPager: {
    flex: 1,
    minHeight: 0,
  },
  onboardingPagerContent: {
    alignItems: 'stretch',
  },
  onboardingSlide: {
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingHorizontal: 2,
    paddingTop: 6,
  },
  onboardingImage: {
    width: '100%',
    maxWidth: 330,
    marginBottom: 18,
  },
  onboardingTitle: {
    maxWidth: 330,
    color: palette.ink,
    fontSize: 23,
    lineHeight: 34,
    fontWeight: '900',
    textAlign: 'center',
  },
  onboardingBody: {
    maxWidth: 330,
    marginTop: 12,
    color: palette.muted,
    fontSize: 15,
    lineHeight: 24,
    textAlign: 'center',
  },
  onboardingActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 12,
  },
  onboardingLoginButton: {
    flex: 1,
    height: 50,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.amber,
  },
  onboardingSignupButton: {
    flex: 1,
    height: 50,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.green,
  },
  onboardingLoginText: {
    color: palette.ink,
    fontSize: 15,
    fontWeight: '900',
    textAlign: 'center',
  },
  onboardingSignupText: {
    color: palette.white,
    fontSize: 15,
    fontWeight: '900',
    textAlign: 'center',
  },
  onboardingFooter: {
    minHeight: 54,
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  onboardingArrow: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: palette.border,
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 2,
  },
  onboardingArrowActive: {
    backgroundColor: palette.green,
    borderColor: palette.green,
  },
  onboardingArrowDisabled: {
    opacity: 0.35,
    backgroundColor: palette.white,
    borderColor: palette.border,
  },
  onboardingDots: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  onboardingDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#D2D5D7',
  },
  onboardingDotActive: {
    backgroundColor: palette.green,
  },
  rtlText: {
    writingDirection: 'rtl',
    textAlign: 'right',
    color: palette.ink,
    fontFamily,
  },
  header: {
    minHeight: 54,
    paddingTop: 2,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  headerCompact: {
    paddingTop: 0,
  },
  headerActions: {
    flexDirection: 'row',
    gap: 10,
  },
  roundIconGhost: {
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 17,
    backgroundColor: palette.white,
  },
  headerBadge: {
    position: 'absolute',
    top: -3,
    right: -3,
    minWidth: 16,
    height: 16,
    paddingHorizontal: 4,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.danger,
    borderWidth: 1.5,
    borderColor: palette.white,
  },
  headerBadgeText: {
    color: palette.white,
    fontSize: 8,
    fontWeight: '900',
    textAlign: 'center',
  },
  headerTitle: {
    fontSize: 14,
    fontWeight: '700',
    minWidth: 72,
  },
  searchWrap: {
    flex: 1,
    minWidth: 0,
    height: 42,
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 24,
    backgroundColor: '#F2F3F4',
    paddingHorizontal: 5,
  },
  searchButton: {
    width: 38,
    height: 38,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.green,
  },
  searchInput: {
    flex: 1,
    paddingHorizontal: 10,
    fontSize: 12,
    color: palette.ink,
    writingDirection: 'rtl',
    outlineStyle: 'none',
    outlineWidth: 0,
    boxShadow: 'none',
  },
  promoSlider: {
    height: 116,
    marginTop: 10,
    borderRadius: 8,
    overflow: 'hidden',
  },
  promoBanner: {
    height: 116,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: palette.green,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    paddingHorizontal: 14,
  },
  promoText: {
    flex: 1,
    alignItems: 'flex-end',
  },
  promoTitle: {
    color: palette.white,
    fontSize: 18,
    fontWeight: '900',
  },
  promoBody: {
    color: '#E7FFF7',
    fontSize: 12,
    lineHeight: 18,
    marginTop: 4,
    maxWidth: 230,
  },
  promoButton: {
    marginTop: 10,
    height: 30,
    paddingHorizontal: 12,
    borderRadius: 16,
    backgroundColor: palette.white,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  promoButtonText: {
    fontSize: 12,
    fontWeight: '800',
    color: palette.greenDark,
  },
  promoImage: {
    width: 126,
    height: 98,
    borderRadius: 8,
    resizeMode: 'cover',
    marginRight: 10,
  },
  promoDots: {
    position: 'absolute',
    bottom: 12,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 4,
  },
  promoDot: {
    width: 5,
    height: 5,
    borderRadius: 3,
    backgroundColor: '#FFFFFF80',
  },
  promoDotActive: {
    width: 14,
    backgroundColor: palette.white,
  },
  categoryStrip: {
    marginTop: 18,
    flexDirection: 'row-reverse',
    justifyContent: 'flex-start',
    flexWrap: 'wrap',
    columnGap: 15,
    rowGap: 10,
  },
  categoryStripDouble: {
    flexWrap: 'wrap',
    justifyContent: 'flex-end',
    rowGap: 12,
  },
  categoryItem: {
    width: 58,
    alignItems: 'center',
  },
  categoryImageWrap: {
    width: 52,
    height: 52,
    borderRadius: 25,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#F1F3F4',
  },
  categoryImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  categoryLabel: {
    marginTop: 6,
    fontSize: 11,
    color: palette.ink,
    textAlign: 'center',
  },
  sectionTitle: {
    marginTop: 16,
    marginBottom: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionName: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  sectionHeading: {
    fontSize: 18,
    fontWeight: '900',
  },
  sectionAction: {
    fontSize: 12,
    fontWeight: '700',
    color: palette.green,
  },
  rtlHorizontalScroll: {
    transform: [{ scaleX: -1 }],
  },
  rtlHorizontalContent: {
    flexDirection: 'row',
  },
  rtlHorizontalItem: {
    transform: [{ scaleX: -1 }],
  },
  horizontalCards: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 2,
    paddingBottom: 4,
  },
  reelCard: {
    width: 118,
    height: 156,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#111',
  },
  reelThumb: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  reelPlay: {
    position: 'absolute',
    top: 8,
    left: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  reelCount: {
    color: palette.white,
    fontSize: 10,
    fontWeight: '800',
  },
  reelMeta: {
    position: 'absolute',
    bottom: 8,
    right: 8,
    left: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
  },
  miniCart: {
    width: 28,
    height: 28,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.white,
  },
  notificationList: {
    gap: 10,
  },
  notificationItem: {
    minHeight: 64,
    borderRadius: 8,
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 12,
    flexDirection: 'row-reverse',
    alignItems: 'flex-start',
    gap: 10,
  },
  notificationDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    marginTop: 5,
    backgroundColor: palette.amber,
  },
  notificationDotRead: {
    backgroundColor: palette.border,
  },
  notificationBody: {
    flex: 1,
  },
  notificationTitle: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: '900',
    textAlign: 'right',
  },
  notificationText: {
    marginTop: 4,
    color: palette.muted,
    fontSize: 12,
    lineHeight: 18,
    textAlign: 'right',
  },
  reelTitle: {
    flex: 1,
    color: palette.white,
    fontSize: 11,
    fontWeight: '800',
  },
  couponCard: {
    width: 134,
    height: 90,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  ticketCutLeft: {
    position: 'absolute',
    left: -8,
    top: 34,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: palette.white,
  },
  ticketCutRight: {
    position: 'absolute',
    right: -8,
    top: 34,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: palette.white,
  },
  couponPrice: {
    color: palette.white,
    fontSize: 16,
    fontWeight: '900',
  },
  couponCode: {
    marginTop: 4,
    color: '#E8FFF7',
    fontSize: 10,
    fontWeight: '700',
  },
  copyButton: {
    marginTop: 8,
    width: 74,
    height: 24,
    borderRadius: 12,
    backgroundColor: palette.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  copyButtonText: {
    color: palette.greenDark,
    fontSize: 11,
    fontWeight: '800',
    textAlign: 'center',
  },
  couponIndex: {
    position: 'absolute',
    bottom: 6,
    left: 8,
    color: '#FFFFFF80',
    fontSize: 10,
  },
  productGrid: {
    marginTop: 10,
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    columnGap: 10,
    rowGap: 13,
  },
  collectionContent: {
    paddingHorizontal: 16,
    paddingBottom: 120,
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
  },
  collectionHeader: {
    minHeight: 64,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  collectionHeaderText: {
    flex: 1,
    alignItems: 'flex-end',
  },
  collectionTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  collectionTitle: {
    fontSize: 20,
    fontWeight: '900',
  },
  collectionSub: {
    marginTop: 4,
    color: palette.muted,
    fontSize: 12,
  },
  collectionGrid: {
    marginTop: 14,
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 14,
  },
  collectionCardThreeColumns: {
    width: '31.5%',
  },
  collectionCardFourColumns: {
    width: '23.5%',
  },
  collectionReelTile: {
    width: '48%',
    aspectRatio: 0.74,
  },
  collectionReelCard: {
    width: '100%',
    height: '100%',
  },
  collectionCouponTile: {
    width: '48%',
  },
  collectionCouponCard: {
    width: '100%',
    height: 112,
  },
  collectionEmpty: {
    marginTop: 34,
    color: palette.muted,
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'center',
  },
  productCard: {
    width: '48%',
    backgroundColor: palette.white,
    borderRadius: 8,
    padding: 6,
    borderWidth: 1,
    borderColor: palette.border,
    shadowColor: '#0F211C',
    shadowOpacity: 0.08,
    shadowRadius: 12,
    shadowOffset: { width: 0, height: 5 },
    elevation: 2,
  },
  productCardShowcase: {
    borderRadius: 14,
    padding: 7,
    borderColor: '#EDF1F1',
    shadowColor: '#0B211B',
    shadowOpacity: 0.16,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 7 },
    elevation: 4,
  },
  productCardCompact: {
    width: 176,
  },
  productCardThreeColumns: {
    width: '31.5%',
  },
  productCardFourColumns: {
    width: '23.5%',
  },
  productCardWideCompact: {
    width: 184,
  },
  productImageBox: {
    aspectRatio: 0.98,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#F2F3F2',
  },
  productImageBoxShowcase: {
    aspectRatio: 1.06,
    borderRadius: 10,
  },
  productImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  heartButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#00000055',
  },
  productBadges: {
    position: 'absolute',
    left: 7,
    bottom: 7,
    right: 7,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  productBadgesShowcase: {
    left: 10,
    //right: 30,
    bottom: 10,
    justifyContent: 'flex-end',
    gap: 6,
  },
  ratingPill: {
    height: 22,
    paddingHorizontal: 7,
    borderRadius: 11,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    backgroundColor: '#00000066',
  },
  ratingText: {
    color: palette.white,
    fontSize: 10,
    fontWeight: '800',
  },
  deliveryPill: {
    height: 22,
    paddingHorizontal: 7,
    borderRadius: 11,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 3,
    justifyContent: 'center',
    backgroundColor: '#00000066',
  },
  deliveryText: {
    color: palette.white,
    fontSize: 9,
    fontWeight: '700',
  },
  productTitle: {
    marginTop: 8,
    minHeight: 38,
    fontSize: 14,
    lineHeight: 18,
    fontWeight: '900',
  },
  productTitleShowcase: {
    marginTop: 8,
    minHeight: 32,
    fontSize: 13,
    lineHeight: 16,
    textAlign: 'right',
  },
  storeLine: {
    marginTop: 2,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 5,
  },
  storeAvatar: {
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: '#CBD3D8',
  },
  storeName: {
    flex: 1,
    color: palette.muted,
    fontSize: 10,
  },
  productPrice: {
    marginTop: 7,
    fontSize: 18,
    color: palette.green,
    fontWeight: '900',
  },
  productPriceShowcase: {
    marginTop: 4,
    fontSize: 18,
    textAlign: 'right',
  },
  productCart: {
    marginTop: 6,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.greenSoft,
  },
  productCartShowcase: {
    height: 30,
    borderRadius: 15,
    backgroundColor: '#E9FFF8',
  },
  detailsContent: {
    paddingBottom: 120,
    width: '100%',
    maxWidth: 900,
    alignSelf: 'center',
    backgroundColor: palette.white,
  },
  detailsTopBar: {
    height: 54,
    paddingHorizontal: 16,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  detailsTopButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.greenSoft,
  },
  detailsHeaderTitle: {
    fontSize: 16,
    fontWeight: '900',
    textAlign: 'center',
  },
  detailsImageWrap: {
    marginHorizontal: 16,
    aspectRatio: 1.12,
    maxHeight: 360,
    borderRadius: 8,
    overflow: 'hidden',
    backgroundColor: '#F0F2F2',
  },
  detailsImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  detailsFavorite: {
    position: 'absolute',
    top: 14,
    right: 14,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#00000055',
  },
  detailsDots: {
    position: 'absolute',
    bottom: 14,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 6,
  },
  detailsDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: '#FFFFFF99',
  },
  detailsDotActive: {
    width: 20,
    height: 7,
    borderRadius: 4,
    backgroundColor: palette.white,
  },
  detailsBody: {
    padding: 16,
  },
  detailsBadgeRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  detailsDelivery: {
    height: 30,
    paddingHorizontal: 10,
    borderRadius: 15,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 5,
    backgroundColor: palette.greenSoft,
  },
  detailsDeliveryText: {
    color: palette.green,
    fontSize: 11,
    fontWeight: '800',
  },
  detailsRating: {
    height: 30,
    paddingHorizontal: 10,
    borderRadius: 15,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: palette.amberSoft,
  },
  detailsRatingText: {
    fontSize: 12,
    fontWeight: '900',
  },
  detailsTitle: {
    alignSelf: 'stretch',
    marginTop: 14,
    fontSize: 21,
    lineHeight: 29,
    fontWeight: '900',
  },
  detailsStoreRow: {
    marginTop: 14,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 10,
  },
  detailsStoreAvatar: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#D8DDDF',
  },
  detailsStoreName: {
    fontSize: 13,
    fontWeight: '900',
  },
  detailsStoreButton: {
    height: 32,
    paddingHorizontal: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.green,
    justifyContent: 'center',
  },
  detailsStoreButtonText: {
    color: palette.green,
    fontSize: 11,
    fontWeight: '900',
    textAlign: 'center',
  },
  detailsPrice: {
    marginTop: 18,
    color: palette.green,
    fontSize: 25,
    fontWeight: '900',
  },
  detailsDivider: {
    height: 1,
    marginVertical: 18,
    backgroundColor: palette.border,
  },
  detailsSectionTitle: {
    fontSize: 15,
    fontWeight: '900',
  },
  detailsDescription: {
    alignSelf: 'stretch',
    marginTop: 8,
    color: palette.muted,
    fontSize: 13,
    lineHeight: 22,
  },
  detailsQuantityRow: {
    marginTop: 22,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  detailsQuantity: {
    height: 38,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  detailsQtyButton: {
    width: 34,
    height: 34,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.greenSoft,
  },
  detailsQtyValue: {
    minWidth: 22,
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  detailsAddButton: {
    marginTop: 24,
    height: 60,
    borderRadius: 8,
    paddingHorizontal: 20,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: palette.green,
  },
  detailsAddText: {
    color: palette.white,
    fontSize: 16,
    fontWeight: '900',
  },
  detailsAddSub: {
    marginTop: 2,
    color: '#DFFFF5',
    fontSize: 11,
  },
  emptyCart: {
    flex: 1,
    paddingHorizontal: 30,
    paddingBottom: 90,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyCartIcon: {
    width: 88,
    height: 88,
    borderRadius: 44,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.greenSoft,
  },
  emptyCartMascot: {
    width: 210,
    height: 170,
    alignSelf: 'center',
    marginBottom: 4,
  },
  emptyCartTitle: {
    marginTop: 18,
    fontSize: 22,
    fontWeight: '900',
    textAlign: 'center',
  },
  emptyCartText: {
    marginTop: 8,
    color: palette.muted,
    fontSize: 13,
    textAlign: 'center',
  },
  emptyCartButton: {
    marginTop: 22,
    height: 46,
    paddingHorizontal: 30,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.green,
  },
  emptyCartButtonText: {
    color: palette.white,
    fontWeight: '900',
    textAlign: 'center',
  },
  guestCartTopBar: {
    minHeight: 72,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  guestCartHeader: {
    color: palette.ink,
    fontSize: 21,
    fontWeight: '900',
    textAlign: 'right',
  },
  guestCartImage: {
    width: '100%',
    height: 360,
    alignSelf: 'center',
    marginTop: 8,
    marginBottom: 2,
  },
  guestCartTitle: {
    color: palette.ink,
    fontSize: 19,
    lineHeight: 28,
    fontWeight: '900',
    textAlign: 'center',
    marginTop: 4,
  },
  guestCartActions: {
    marginTop: 26,
    marginBottom: 26,
    flexDirection: 'row',
    gap: 14,
  },
  guestCartButton: {
    flex: 1,
    minHeight: 54,
    borderRadius: 27,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#10231E',
    shadowOpacity: 0.12,
    shadowRadius: 13,
    shadowOffset: { width: 0, height: 7 },
    elevation: 3,
  },
  guestCartExplore: {
    backgroundColor: palette.green,
  },
  guestCartLogin: {
    backgroundColor: palette.amber,
  },
  guestCartButtonText: {
    color: palette.white,
    fontSize: 19,
    fontWeight: '900',
    textAlign: 'center',
  },
  guestCartLoginText: {
    color: palette.ink,
  },
  cartScreen: {
    flex: 1,
    backgroundColor: palette.white,
  },
  cartContent: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 214,
    width: '100%',
    maxWidth: 430,
    alignSelf: 'center',
  },
  cartContentSummaryStep: {
    paddingBottom: 28,
  },
  cartTopBar: {
    height: 120,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cartMiniTitle: {
    position: 'absolute',
    top: 3,
    left: 0,
    fontSize: 12,
    fontWeight: '900',
  },
  cartTitle: {
    marginTop: 18,
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  cartBackButton: {
    position: 'absolute',
    top: 54,
    right: 2,
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1.8,
    borderColor: palette.green,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.white,
  },
  cartSelectionBar: {
    marginTop: 6,
    marginBottom: 16,
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cartSelectionInfo: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 12,
  },
  cartSelectionTitle: {
    fontSize: 16,
    fontWeight: '900',
  },
  cartCheckmark: {
    width: 11,
    height: 11,
    borderRadius: 2,
    borderWidth: 1.4,
    borderColor: palette.green,
    backgroundColor: palette.white,
  },
  cartTrashButton: {
    width: 31,
    height: 31,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: '#E8EFF3',
    shadowColor: '#0D2A23',
    shadowOpacity: 0.09,
    shadowRadius: 9,
    shadowOffset: { width: 0, height: 4 },
    elevation: 3,
  },
  cartItem: {
    position: 'relative',
    minHeight: 115,
    marginBottom: 18,
    padding: 8,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#E6EAED',
    flexDirection: 'row-reverse',
    gap: 13,
    backgroundColor: palette.white,
    shadowColor: '#10231E',
    shadowOpacity: 0.11,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  cartItemCheckbox: {
    position: 'absolute',
    top: 16,
    left: 16,
    zIndex: 2,
  },
  cartItemImage: {
    width: 99,
    height: 99,
    borderRadius: 14,
    resizeMode: 'cover',
  },
  cartItemImageFallback: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.greenSoft,
  },
  cartItemBody: {
    flex: 1,
    alignItems: 'flex-end',
    minWidth: 0,
    paddingTop: 12,
    paddingBottom: 40,
  },
  cartItemTitle: {
    alignSelf: 'stretch',
    fontSize: 16,
    lineHeight: 22,
    fontWeight: '500',
    color: palette.ink,
  },
  cartItemStoreRow: {
    marginTop: 4,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 7,
  },
  cartStoreAvatar: {
    width: 17,
    height: 17,
    borderRadius: 9,
    overflow: 'hidden',
    backgroundColor: '#26313A',
  },
  cartStoreAvatarImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  cartItemStore: {
    color: palette.ink,
    fontSize: 11,
    fontWeight: '500',
  },
  cartItemColor: {
    marginTop: 8,
    color: '#7D8792',
    fontSize: 12,
  },
  cartPriceRow: {
    marginTop: 5,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 7,
  },
  cartItemPrice: {
    color: palette.green,
    fontSize: 14,
    fontWeight: '900',
  },
  cartOldPrice: {
    color: '#A8AFBA',
    fontSize: 10,
    textDecorationLine: 'line-through',
  },
  cartQty: {
    position: 'absolute',
    left: 0,
    bottom: 8,
    width: 82,
    height: 32,
    borderRadius: 17,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: '#F2F3F4',
    shadowColor: '#0E211D',
    shadowOpacity: 0.06,
    shadowRadius: 7,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  cartQtyButton: {
    width: 24,
    height: 28,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cartQtyValue: {
    minWidth: 20,
    fontSize: 18,
    fontWeight: '500',
    textAlign: 'center',
  },
  cartRemove: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 4,
  },
  cartRemoveText: {
    color: palette.danger,
    fontSize: 11,
    fontWeight: '800',
  },
  cartCouponBanner: {
    minHeight: 59,
    marginTop: 13,
    marginBottom: 28,
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 12,
    backgroundColor: palette.greenSoft,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  cartCouponInfo: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 13,
  },
  cartCouponTextBlock: {
    flex: 1,
    minWidth: 0,
    alignItems: 'flex-end',
  },
  cartCouponTitle: {
    color: palette.greenDark,
    fontSize: 15,
    fontWeight: '900',
  },
  cartCouponInput: {
    width: '100%',
    marginTop: 4,
    paddingVertical: 0,
    paddingHorizontal: 0,
    color: palette.greenDark,
    fontSize: 13,
    fontWeight: '700',
    outlineStyle: 'none',
    outlineWidth: 0,
    boxShadow: 'none',
    writingDirection: 'rtl',
  },
  cartCouponApplied: {
    marginTop: 4,
    color: palette.green,
    fontSize: 11,
    fontWeight: '800',
  },
  cartCouponAction: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  cartCouponActionText: {
    color: palette.green,
    fontSize: 12,
    fontWeight: '800',
  },
  cartSummary: {
    marginTop: 0,
    padding: 16,
    borderRadius: 18,
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: '#E8EAEC',
    shadowColor: '#10231E',
    shadowOpacity: 0.12,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
  },
  cartSummaryTitle: {
    marginBottom: 15,
    fontSize: 18,
    fontWeight: '900',
  },
  cartSummaryDashed: {
    overflow: 'hidden',
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#DFE3E6',
    borderRadius: 20,
  },
  cartReceiptLine: {
    minHeight: 41,
    paddingHorizontal: 11,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: '#E9ECEF',
  },
  cartReceiptLineStrong: {
    minHeight: 67,
    borderBottomWidth: 0,
  },
  cartReceiptLabel: {
    color: '#787878',
    fontSize: 16,
    fontWeight: '400',
  },
  cartReceiptLabelStrong: {
    color: palette.ink,
    fontWeight: '700',
  },
  cartReceiptValue: {
    color: palette.ink,
    fontSize: 16,
    fontWeight: '900',
    textAlign: 'left',
  },
  cartReceiptValueStrong: {
    fontSize: 18,
  },
  cartSummaryLine: {
    marginTop: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cartSummaryLabel: {
    color: palette.muted,
    fontSize: 13,
  },
  cartSummaryValue: {
    fontSize: 13,
    fontWeight: '800',
  },
  cartSummaryFree: {
    color: palette.green,
    fontSize: 13,
    fontWeight: '900',
  },
  cartSummaryDivider: {
    height: 1,
    marginVertical: 14,
    backgroundColor: palette.border,
  },
  cartTotalLabel: {
    fontSize: 15,
    fontWeight: '900',
  },
  cartTotalValue: {
    color: palette.green,
    fontSize: 19,
    fontWeight: '900',
  },
  checkoutButton: {
    marginTop: 16,
    height: 48,
    borderRadius: 24,
    paddingHorizontal: 18,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    backgroundColor: palette.green,
  },
  checkoutText: {
    color: palette.white,
    fontSize: 16,
    fontWeight: '500',
    textAlign: 'center',
  },
  cartCheckoutSheet: {
    position: 'absolute',
    left: 16,
    right: 16,
    bottom: 14,
    minHeight: 118,
    padding: 16,
    borderRadius: 16,
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: '#E8EAEC',
    shadowColor: '#10231E',
    shadowOpacity: 0.14,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  cartCheckoutMeta: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  cartCheckoutTotal: {
    color: palette.green,
    fontSize: 19,
    fontWeight: '900',
    textAlign: 'left',
  },
  cartCheckoutButton: {
    marginTop: 16,
    height: 48,
    borderRadius: 24,
    paddingHorizontal: 18,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
    backgroundColor: palette.green,
  },
  cartCheckoutText: {
    color: palette.white,
    fontSize: 14,
    fontWeight: '500',
    textAlign: 'center',
  },
  checkoutContent: {
    paddingHorizontal: 16,
    paddingBottom: 120,
    width: '100%',
    maxWidth: 900,
    alignSelf: 'center',
  },
  detailsTopSpacer: {
    width: 36,
    height: 36,
  },
  checkoutSectionTitle: {
    alignSelf: 'stretch',
    marginTop: 14,
    marginBottom: 10,
    fontSize: 16,
    fontWeight: '900',
  },
  checkoutPanel: {
    padding: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.white,
  },
  paymentOptions: {
    gap: 10,
  },
  paymentOption: {
    minHeight: 72,
    padding: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.border,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 12,
    backgroundColor: palette.white,
  },
  paymentOptionActive: {
    borderColor: palette.green,
    backgroundColor: palette.greenSoft,
  },
  paymentRadio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#B8C0C5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  paymentRadioActive: {
    borderColor: palette.green,
  },
  paymentRadioDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: palette.green,
  },
  paymentTitle: {
    fontSize: 13,
    fontWeight: '900',
  },
  checkoutSummary: {
    marginTop: 20,
    marginBottom: 8,
    padding: 16,
    borderRadius: 8,
    backgroundColor: '#F6F8F7',
  },
  successScreen: {
    flex: 1,
    paddingHorizontal: 28,
    paddingBottom: 90,
    alignItems: 'center',
    justifyContent: 'center',
  },
  successIcon: {
    width: 96,
    height: 96,
    borderRadius: 48,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.green,
  },
  successMascot: {
    width: 190,
    height: 170,
    borderRadius: 24,
  },
  successTitle: {
    marginTop: 22,
    fontSize: 24,
    fontWeight: '900',
    textAlign: 'center',
  },
  successText: {
    maxWidth: 300,
    marginTop: 9,
    color: palette.muted,
    fontSize: 13,
    lineHeight: 21,
    textAlign: 'center',
  },
  successOrderNumber: {
    width: '100%',
    marginTop: 24,
    padding: 16,
    borderRadius: 8,
    alignItems: 'center',
    backgroundColor: palette.greenSoft,
  },
  successNumber: {
    marginTop: 5,
    color: palette.greenDark,
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  successButton: {
    marginTop: 24,
    height: 48,
    paddingHorizontal: 28,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.green,
  },
  successButtonText: {
    color: palette.white,
    fontSize: 14,
    fontWeight: '900',
    textAlign: 'center',
  },
  offerBand: {
    marginTop: 4,
    flexDirection: 'row',
    gap: 12,
  },
  offerCard: {
    flex: 1,
    minHeight: 84,
    borderRadius: 8,
    padding: 10,
    overflow: 'hidden',
    backgroundColor: palette.greenSoft,
    borderWidth: 1,
    borderColor: '#CEF1E8',
    flexDirection: 'row-reverse',
    alignItems: 'center',
  },
  offerCardAmber: {
    backgroundColor: palette.amberSoft,
    borderColor: '#FFE0A0',
  },
  offerImage: {
    width: 58,
    height: 64,
    resizeMode: 'cover',
    borderRadius: 6,
  },
  offerText: {
    flex: 1,
    alignItems: 'flex-end',
  },
  offerTitle: {
    color: palette.greenDark,
    fontSize: 13,
    fontWeight: '900',
  },
  offerSub: {
    marginTop: 3,
    color: palette.muted,
    fontSize: 9,
    lineHeight: 14,
  },
  offerButton: {
    marginTop: 7,
    height: 24,
    paddingHorizontal: 11,
    borderRadius: 12,
    backgroundColor: palette.green,
    justifyContent: 'center',
  },
  offerButtonAmber: {
    backgroundColor: palette.amber,
  },
  offerButtonText: {
    color: palette.white,
    fontSize: 9,
    fontWeight: '900',
    textAlign: 'center',
  },
  tabs: {
    flexDirection: 'row',
    gap: 12,
    paddingTop: 14,
    paddingBottom: 8,
  },
  tabsCompact: {
    paddingHorizontal: 14,
    paddingTop: 8,
    paddingBottom: 8,
  },
  tabItem: {
    minHeight: 34,
    justifyContent: 'center',
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  tabItemActive: {
    borderBottomColor: palette.ink,
  },
  tabText: {
    color: palette.muted,
    fontSize: 14,
    fontWeight: '700',
  },
  tabTextActive: {
    color: palette.ink,
    fontSize: 17,
    fontWeight: '900',
  },
  storeInner: {
    paddingHorizontal: 16,
    paddingBottom: 120,
    width: '100%',
    maxWidth: 1180,
    alignSelf: 'center',
  },
  storeTopActions: {
    marginTop: 8,
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  storeScreenTitle: {
    flex: 1,
    textAlign: 'center',
    fontWeight: '800',
  },
  greenTiny: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: palette.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  storeHero: {
    width: '100%',
    minHeight: 108,
    maxHeight: 260,
    aspectRatio: 3.4,
    borderRadius: 8,
    resizeMode: 'cover',
  },
  storeStats: {
    marginTop: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.border,
    flexDirection: 'row-reverse',
    overflow: 'hidden',
  },
  metric: {
    flex: 1,
    minHeight: 76,
    alignItems: 'center',
    justifyContent: 'center',
    borderLeftWidth: 1,
    borderLeftColor: palette.border,
  },
  metricLabel: {
    marginTop: 5,
    color: palette.muted,
    fontSize: 9,
    textAlign: 'center',
  },
  metricValue: {
    marginTop: 3,
    fontSize: 10,
    fontWeight: '800',
    textAlign: 'center',
  },
  storeRatingCard: {
    marginTop: 18,
    padding: 14,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.border,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 16,
  },
  ratingScoreBox: {
    width: 82,
    alignItems: 'center',
  },
  bigRating: {
    fontSize: 36,
    fontWeight: '900',
  },
  starsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
  },
  tinyMuted: {
    color: palette.muted,
    fontSize: 11,
  },
  ratingBars: {
    flex: 1,
    gap: 7,
  },
  ratingBarLine: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
  },
  ratingLabel: {
    width: 42,
    color: palette.muted,
    fontSize: 10,
  },
  ratingTrack: {
    flex: 1,
    height: 6,
    borderRadius: 4,
    backgroundColor: '#EDF0F1',
    overflow: 'hidden',
  },
  ratingFill: {
    height: '100%',
    borderRadius: 4,
    backgroundColor: palette.green,
  },
  storeCardGrid: {
    marginTop: 12,
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 14,
  },
  storeMiniCard: {
    width: '48%',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 8,
  },
  storeMiniCardThreeColumns: {
    width: '31.5%',
  },
  storeMiniCardFourColumns: {
    width: '23.5%',
  },
  storeMiniImage: {
    width: '100%',
    aspectRatio: 1.45,
    borderRadius: 8,
    resizeMode: 'cover',
  },
  storeMiniTitle: {
    marginTop: 7,
    fontWeight: '900',
    fontSize: 13,
  },
  storeMiniSub: {
    color: palette.muted,
    fontSize: 10,
  },
  storeMiniRating: {
    marginTop: 4,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'center',
    gap: 3,
  },
  storeMiniRatingText: {
    fontSize: 10,
    color: palette.muted,
  },
  visitButton: {
    marginTop: 8,
    height: 30,
    borderRadius: 15,
    backgroundColor: palette.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  visitText: {
    color: palette.white,
    fontSize: 11,
    fontWeight: '800',
    textAlign: 'center',
  },
  rateButton: {
    flex: 1,
    height: 42,
    borderRadius: 21,
    backgroundColor: palette.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rateButtonText: {
    color: palette.white,
    fontWeight: '900',
    textAlign: 'center',
  },
  commentHeader: {
    marginTop: 16,
    marginBottom: 6,
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  commentCard: {
    minHeight: 92,
    marginTop: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 12,
    flexDirection: 'row-reverse',
    gap: 10,
    alignItems: 'center',
  },
  commentAvatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: '#E7EAED',
    alignItems: 'center',
    justifyContent: 'center',
  },
  commentContent: {
    flex: 1,
    alignItems: 'flex-end',
  },
  commentName: {
    fontWeight: '900',
  },
  commentText: {
    marginTop: 6,
    fontSize: 12,
    color: palette.ink,
  },
  commentDate: {
    alignSelf: 'flex-start',
    color: palette.muted,
    fontSize: 10,
  },
  rateScreen: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
    width: '100%',
    maxWidth: 900,
    alignSelf: 'center',
  },
  reviewStoreHeader: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 12,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
  },
  storeAvatarLarge: {
    width: 76,
    height: 76,
    borderRadius: 8,
    backgroundColor: '#F0F1F2',
  },
  reviewStoreName: {
    fontSize: 17,
    fontWeight: '900',
  },
  categoryChipText: {
    alignSelf: 'flex-end',
    marginTop: 5,
    paddingHorizontal: 10,
    paddingVertical: 3,
    borderRadius: 12,
    backgroundColor: palette.greenSoft,
    color: palette.green,
    fontSize: 10,
    fontWeight: '800',
  },
  locationLine: {
    marginTop: 8,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 4,
  },
  rateQuestion: {
    marginTop: 24,
    fontSize: 15,
    fontWeight: '800',
    textAlign: 'center',
  },
  rateStars: {
    marginTop: 14,
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 12,
  },
  rateWord: {
    marginTop: 8,
    color: palette.green,
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
  },
  commentBox: {
    marginTop: 16,
    minHeight: 92,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 14,
    color: palette.ink,
    textAlignVertical: 'top',
  },
  uploadRow: {
    marginTop: 14,
    flexDirection: 'row-reverse',
    gap: 10,
  },
  uploadBox: {
    flex: 1,
    height: 86,
    borderRadius: 8,
    backgroundColor: '#F0F1F1',
  },
  uploadDashed: {
    flex: 1,
    height: 86,
    borderRadius: 8,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: '#AAB3BA',
    alignItems: 'center',
    justifyContent: 'center',
  },
  uploadText: {
    marginTop: 6,
    color: palette.muted,
    fontSize: 11,
    textAlign: 'center',
  },
  submitButton: {
    marginTop: 'auto',
    marginBottom: 24,
    height: 50,
    borderRadius: 8,
    backgroundColor: palette.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  submitText: {
    color: palette.white,
    fontSize: 16,
    fontWeight: '900',
    textAlign: 'center',
  },
  reelsScreen: {
    flex: 1,
    minHeight: 760,
    backgroundColor: '#051B20',
  },
  reelsBackground: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  reelsOverlay: {
    flex: 1,
    justifyContent: 'space-between',
    paddingTop: 18,
    paddingBottom: 18,
  },
  reelsTopButtons: {
    paddingHorizontal: 18,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  reelsLeftButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  reelsButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: palette.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reelsCartSheet: {
    marginHorizontal: 16,
    padding: 16,
    borderRadius: 8,
    backgroundColor: palette.white,
  },
  qtyRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sheetPrice: {
    color: palette.green,
    fontSize: 18,
    fontWeight: '900',
  },
  qtyControls: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  qtyButton: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: palette.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  qtyValue: {
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  qtyLabel: {
    fontSize: 12,
    color: palette.ink,
  },
  addToCartButton: {
    marginTop: 16,
    height: 48,
    borderRadius: 24,
    backgroundColor: palette.green,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  addToCartText: {
    color: palette.white,
    fontSize: 14,
    fontWeight: '900',
    textAlign: 'center',
  },
  authTabs: {
    marginTop: 18,
    alignSelf: 'center',
    flexDirection: 'row-reverse',
    borderRadius: 20,
    backgroundColor: '#F2F4F4',
    padding: 4,
  },
  authTab: {
    height: 32,
    paddingHorizontal: 14,
    borderRadius: 16,
    justifyContent: 'center',
  },
  authTabActive: {
    backgroundColor: palette.green,
  },
  authTabText: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
  },
  authTabTextActive: {
    color: palette.white,
  },
  authTitle: {
    marginTop: 84,
    marginBottom: 28,
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '900',
  },
  authHint: {
    marginTop: -10,
    marginBottom: 18,
    color: palette.muted,
    fontSize: 13,
    lineHeight: 21,
    textAlign: 'center',
  },
  authFieldBlock: {
    flex: 1,
    minWidth: 0,
    marginBottom: 14,
  },
  authLabel: {
    marginBottom: 8,
    fontSize: 13,
    fontWeight: '700',
    color: palette.ink,
    textAlign: 'right',
  },
  authInputShell: {
    height: 52,
    minWidth: 0,
    borderRadius: 18,
    borderWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingHorizontal: 16,
    backgroundColor: palette.white,
    shadowColor: '#10231E',
    shadowOpacity: 0.1,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 7 },
    elevation: 3,
  },
  authInput: {
    flex: 1,
    minWidth: 0,
    color: palette.ink,
    fontSize: 14,
    textAlign: 'right',
    writingDirection: 'rtl',
    outlineStyle: 'none',
    outlineWidth: 0,
    boxShadow: 'none',
  },
  twoColumns: {
    flexDirection: 'row-reverse',
    gap: 14,
  },
  authFieldHalf: {
    flexBasis: 0,
  },
  authInline: {
    marginBottom: 22,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  rememberRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 5,
  },
  checkbox: {
    width: 12,
    height: 12,
    borderRadius: 2,
    borderWidth: 1.5,
    borderColor: palette.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxChecked: {
    backgroundColor: palette.green,
  },
  linkText: {
    color: palette.green,
    fontWeight: '800',
    fontSize: 12,
    textDecorationLine: 'underline',
  },
  authSignupLink: {
    marginTop: 8,
    color: palette.green,
    fontWeight: '900',
    fontSize: 14,
    lineHeight: 22,
    textAlign: 'center',
    textDecorationLine: 'underline',
  },
  authPrimary: {
    height: 52,
    borderRadius: 14,
    backgroundColor: palette.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  authPrimaryDisabled: {
    opacity: 0.55,
  },
  authInputShellDisabled: {
    backgroundColor: palette.panel,
  },
  editProfileHint: {
    marginTop: 6,
    color: palette.muted,
    fontSize: 11,
    textAlign: 'right',
  },
  editProfileAvatarWrap: {
    alignItems: 'center',
    marginTop: 6,
    marginBottom: 20,
  },
  editProfileAvatar: {
    width: 96,
    height: 96,
    borderRadius: 48,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.green,
    overflow: 'hidden',
  },
  editProfileAvatarImage: {
    width: 96,
    height: 96,
    borderRadius: 48,
  },
  editProfileAvatarBadge: {
    position: 'absolute',
    bottom: 2,
    left: 2,
    width: 28,
    height: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.amber,
    borderWidth: 2,
    borderColor: palette.white,
  },
  editProfileAvatarText: {
    marginTop: 10,
    color: palette.muted,
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
  },
  authPrimaryText: {
    color: palette.white,
    fontSize: 17,
    fontWeight: '900',
    textAlign: 'center',
  },
  authQuestion: {
    marginTop: 18,
    color: palette.ink,
    textAlign: 'center',
    fontSize: 13,
  },
  authInlineQuestion: {
    color: palette.ink,
    textAlign: 'center',
    fontSize: 13,
    lineHeight: 18,
  },
  authQuestionRow: {
    marginTop: 14,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  accountGuestBanner: {
    marginHorizontal: -16,
    marginTop: -10,
    marginBottom: 18,
    minHeight: 225,
    paddingTop: 36,
    paddingHorizontal: 20,
    backgroundColor: '#0F4A3F',
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    overflow: 'hidden',
  },
  accountGuestPattern: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  accountGuestPatternIcon: {
    position: 'absolute',
    opacity: 0.1,
  },
  accountGuestContent: {
    flexDirection: 'row-reverse',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    gap: 8,
    minHeight: 184,
  },
  accountGuestTexts: {
    flex: 1,
    minWidth: 0,
    alignItems: 'flex-end',
    paddingBottom: 34,
    paddingLeft: 4,
  },
  accountGuestTitle: {
    color: palette.white,
    fontSize: 29,
    lineHeight: 39,
    fontWeight: '900',
    textAlign: 'right',
  },
  accountGuestSubtitle: {
    marginTop: 14,
    color: palette.white,
    fontSize: 17,
    lineHeight: 25,
    fontWeight: '700',
    textAlign: 'right',
  },
  accountGuestCta: {
    marginTop: 24,
    minHeight: 50,
    paddingHorizontal: 30,
    borderRadius: 25,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.amber,
    borderWidth: 2,
    borderColor: palette.white,
  },
  accountGuestCtaText: {
    color: palette.ink,
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  accountGuestMascot: {
    width: 176,
    height: 178,
    marginBottom: -10,
    marginLeft: -18,
  },
  accountGuestProductCard: {
    maxWidth: 156,
  },
  accountHeader: {
    marginTop: 18,
    marginBottom: 18,
    padding: 18,
    borderRadius: 8,
    backgroundColor: palette.greenSoft,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 14,
  },
  accountAvatarLarge: {
    width: 72,
    height: 72,
    borderRadius: 36,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: palette.border,
  },
  accountAvatarText: {
    color: palette.green,
    fontSize: 28,
    fontWeight: '900',
    textAlign: 'center',
  },
  accountHeaderText: {
    flex: 1,
    minWidth: 0,
    alignItems: 'flex-end',
  },
  accountTitle: {
    color: palette.ink,
    fontSize: 24,
    lineHeight: 32,
    fontWeight: '900',
    textAlign: 'center',
  },
  accountSubtitle: {
    maxWidth: 360,
    marginTop: 8,
    color: palette.muted,
    fontSize: 14,
    lineHeight: 22,
    textAlign: 'center',
  },
  accountStats: {
    flexDirection: 'row-reverse',
    gap: 10,
    marginBottom: 16,
  },
  accountStat: {
    flex: 1,
    minHeight: 92,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.white,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 10,
  },
  accountStatValue: {
    marginTop: 6,
    color: palette.ink,
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  accountStatLabel: {
    marginTop: 2,
    color: palette.muted,
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
  },
  accountActions: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.white,
    overflow: 'hidden',
  },
  accountAction: {
    minHeight: 58,
    paddingHorizontal: 14,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
  },
  accountActionIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.greenSoft,
  },
  accountActionIconDanger: {
    backgroundColor: '#FFF0F0',
  },
  accountActionText: {
    flex: 1,
    color: palette.ink,
    fontSize: 14,
    fontWeight: '900',
    textAlign: 'right',
  },
  accountActionTextDanger: {
    color: palette.danger,
  },
  accountTopBar: {
    marginTop: 4,
    marginBottom: 14,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  accountBellButton: {
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  accountLocation: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
  },
  accountLocationText: {
    color: palette.ink,
    fontSize: 15,
    fontWeight: '800',
  },
  accountProfileCard: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderRadius: 18,
    backgroundColor: palette.white,
    shadowColor: '#10231E',
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
    marginBottom: 14,
  },
  accountProfileAvatar: {
    width: 54,
    height: 54,
    borderRadius: 27,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.green,
    overflow: 'hidden',
  },
  accountProfileAvatarImage: {
    width: 54,
    height: 54,
    borderRadius: 27,
  },
  accountProfileInfo: {
    flex: 1,
    minWidth: 0,
    alignItems: 'flex-end',
  },
  accountProfileName: {
    color: palette.ink,
    fontSize: 17,
    fontWeight: '900',
    textAlign: 'right',
  },
  accountProfilePhone: {
    marginTop: 3,
    color: palette.muted,
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'right',
  },
  accountMenuCard: {
    borderRadius: 18,
    backgroundColor: palette.white,
    paddingHorizontal: 16,
    shadowColor: '#10231E',
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
    elevation: 3,
  },
  accountMenuRow: {
    minHeight: 68,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 12,
  },
  accountMenuRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: '#F1F3F5',
  },
  accountMenuTexts: {
    flex: 1,
    minWidth: 0,
    alignItems: 'flex-end',
  },
  accountMenuTitle: {
    color: palette.ink,
    fontSize: 15,
    fontWeight: '900',
    textAlign: 'right',
  },
  accountMenuSubtitle: {
    marginTop: 2,
    color: palette.muted,
    fontSize: 12,
    textAlign: 'right',
  },
  accountLogoutButton: {
    marginTop: 18,
    height: 54,
    borderRadius: 16,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: '#FDECEA',
  },
  accountLogoutText: {
    color: palette.danger,
    fontSize: 16,
    fontWeight: '800',
  },
  ordersTabs: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-around',
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
    marginBottom: 14,
  },
  ordersTab: {
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 6,
  },
  ordersTabText: {
    color: palette.muted,
    fontSize: 14,
    fontWeight: '700',
  },
  ordersTabTextActive: {
    color: palette.green,
    fontWeight: '900',
  },
  ordersTabUnderline: {
    marginTop: 6,
    height: 3,
    alignSelf: 'stretch',
    borderRadius: 2,
    backgroundColor: palette.green,
  },
  ordersEmpty: {
    alignItems: 'center',
    paddingVertical: 32,
    paddingHorizontal: 24,
  },
  ordersEmptyImage: {
    width: 200,
    height: 160,
    marginBottom: 12,
  },
  ordersEmptyTitle: {
    color: palette.ink,
    fontSize: 17,
    fontWeight: '900',
  },
  ordersEmptyText: {
    marginTop: 6,
    color: palette.muted,
    fontSize: 13,
    textAlign: 'center',
    lineHeight: 20,
  },
  ordersLoginButton: {
    marginTop: 14,
    height: 44,
    paddingHorizontal: 28,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.green,
  },
  ordersLoginText: {
    color: palette.white,
    fontSize: 14,
    fontWeight: '800',
  },
  orderStatusBadge: {
    width: 30,
    height: 30,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
  orderCard: {
    borderRadius: 18,
    backgroundColor: palette.white,
    borderWidth: 1.5,
    borderColor: palette.border,
    padding: 14,
    marginBottom: 12,
  },
  orderCardDone: {
    borderColor: '#BFE9DC',
  },
  orderCardCancelled: {
    borderColor: '#F5C6C4',
  },
  orderCardTop: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 12,
  },
  orderCardPriceWrap: {
    alignItems: 'flex-start',
  },
  orderCardPrice: {
    color: palette.ink,
    fontSize: 18,
    fontWeight: '900',
  },
  orderCardNumber: {
    marginTop: 3,
    color: palette.green,
    fontSize: 12,
    fontWeight: '700',
  },
  orderCardInfo: {
    flex: 1,
    minWidth: 0,
    alignItems: 'flex-end',
  },
  orderCardTitleRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
  },
  orderCardTitle: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: '800',
  },
  orderCardStore: {
    marginTop: 4,
    color: palette.muted,
    fontSize: 12,
    textAlign: 'right',
  },
  orderCardStoreName: {
    color: palette.ink,
    fontWeight: '800',
  },
  orderCardBottom: {
    marginTop: 12,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  orderTrackButton: {
    height: 36,
    paddingHorizontal: 16,
    borderRadius: 12,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
    backgroundColor: palette.greenDark,
  },
  orderTrackText: {
    color: palette.white,
    fontSize: 13,
    fontWeight: '800',
  },
  orderCardChips: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
  },
  orderChip: {
    height: 30,
    paddingHorizontal: 10,
    borderRadius: 10,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 5,
    backgroundColor: palette.panel,
  },
  orderChipText: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: '700',
  },
  trackSteps: {
    flexDirection: 'row-reverse',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    paddingHorizontal: 8,
    marginTop: 8,
    marginBottom: 22,
  },
  trackStepItem: {
    flex: 1,
    alignItems: 'center',
    gap: 6,
  },
  trackStepDot: {
    width: 16,
    height: 16,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: palette.border,
    backgroundColor: palette.white,
  },
  trackStepDotDone: {
    borderColor: palette.green,
    backgroundColor: palette.green,
  },
  trackStepDotCurrent: {
    borderColor: palette.amber,
    backgroundColor: palette.amber,
  },
  trackStepDotCancelled: {
    borderColor: palette.danger,
    backgroundColor: '#FDECEA',
  },
  trackStepLabel: {
    color: palette.muted,
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
  },
  trackStepLabelActive: {
    color: palette.ink,
  },
  trackHeadline: {
    color: palette.ink,
    fontSize: 22,
    fontWeight: '900',
    textAlign: 'center',
  },
  trackSubline: {
    marginTop: 6,
    color: palette.muted,
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
  },
  trackEta: {
    marginTop: 8,
    color: palette.muted,
    fontSize: 13,
    textAlign: 'center',
  },
  trackEtaValue: {
    color: palette.ink,
    fontWeight: '800',
  },
  trackDivider: {
    height: 1,
    backgroundColor: palette.border,
    marginVertical: 18,
  },
  trackMetaRow: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  trackMetaText: {
    color: palette.muted,
    fontSize: 13,
    fontWeight: '700',
  },
  trackMetaValue: {
    color: palette.ink,
    fontWeight: '900',
  },
  trackSummaryTitle: {
    color: palette.ink,
    fontSize: 16,
    fontWeight: '900',
    textAlign: 'right',
    marginBottom: 12,
  },
  trackSummaryLine: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
  },
  trackSummaryLabel: {
    color: palette.muted,
    fontSize: 13,
    fontWeight: '700',
  },
  trackSummaryValue: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: '800',
  },
  trackSummaryDivider: {
    height: 1,
    backgroundColor: palette.border,
    opacity: 0.7,
  },
  trackSummaryTotal: {
    color: palette.ink,
    fontSize: 17,
    fontWeight: '900',
  },
  trackSummaryTotalLabel: {
    color: palette.ink,
    fontSize: 15,
    fontWeight: '900',
  },
  trackConfirmButton: {
    marginTop: 26,
    height: 54,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.green,
  },
  trackConfirmDisabled: {
    backgroundColor: '#C9CED2',
  },
  trackConfirmText: {
    color: palette.white,
    fontSize: 16,
    fontWeight: '900',
  },
  deliveredMascot: {
    width: 230,
    height: 190,
    alignSelf: 'center',
    marginTop: 8,
  },
  deliveredTitle: {
    marginTop: 14,
    color: palette.ink,
    fontSize: 21,
    fontWeight: '900',
    textAlign: 'center',
  },
  deliveredText: {
    marginTop: 6,
    color: palette.ink,
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
  },
  deliveredStars: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
    marginTop: 14,
    marginBottom: 20,
  },
  deliveredNoteLabel: {
    color: palette.ink,
    fontSize: 13,
    fontWeight: '800',
    textAlign: 'right',
    marginBottom: 8,
  },
  deliveredNoteInput: {
    minHeight: 110,
    borderRadius: 16,
    backgroundColor: palette.panel,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: palette.ink,
    fontSize: 13,
    marginBottom: 20,
  },
  deliveredSubmit: {
    height: 54,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.green,
    marginBottom: 12,
  },
  deliveredSubmitText: {
    color: palette.white,
    fontSize: 16,
    fontWeight: '900',
  },
  deliveredHomeButton: {
    height: 54,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.amber,
    marginBottom: 12,
  },
  deliveredHomeText: {
    color: palette.ink,
    fontSize: 16,
    fontWeight: '900',
  },
  termsRow: {
    marginBottom: 16,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
  },
  bottomNav: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 82,
    backgroundColor: palette.white,
    borderTopWidth: 1,
    borderTopColor: palette.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-around',
    paddingHorizontal: 12,
    paddingBottom: 10,
  },
  bottomItem: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 0,
  },
  bottomCenter: {
    transform: [{ translateY: -16 }],
  },
  navIconWrap: {
    height: 26,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cartBadge: {
    position: 'absolute',
    top: -8,
    right: -11,
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.amber,
    borderWidth: 2,
    borderColor: palette.white,
  },
  cartBadgeText: {
    color: palette.white,
    fontSize: 9,
    fontWeight: '900',
    textAlign: 'center',
  },
  navIconActive: {},
  centerButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: palette.white,
    borderWidth: 8,
    borderColor: '#E5F8F2',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#0F211C',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  bottomLabel: {
    marginTop: 4,
    color: palette.muted,
    fontSize: 11,
    fontWeight: '700',
    textAlign: 'center',
  },
  bottomLabelActive: {
    color: palette.ink,
    fontWeight: '900',
  },
  toast: {
    position: 'absolute',
    left: 44,
    right: 44,
    bottom: 92,
    minHeight: 44,
    paddingHorizontal: 16,
    borderRadius: 22,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: palette.greenDark,
    shadowColor: '#071E18',
    shadowOpacity: 0.18,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 5,
    zIndex: 20,
  },
  toastText: {
    color: palette.white,
    fontSize: 12,
    fontWeight: '900',
    textAlign: 'center',
  },
  modeSwitch: {
    marginTop: 12,
    marginBottom: 10,
    height: 42,
    borderRadius: 22,
    padding: 4,
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: palette.border,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 4,
  },
  modeButton: {
    height: 34,
    paddingHorizontal: 14,
    borderRadius: 18,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
  },
  modeButtonActive: {
    backgroundColor: palette.green,
  },
  modeButtonText: {
    color: palette.green,
    fontSize: 13,
    fontWeight: '900',
    textAlign: 'center',
  },
  modeButtonTextActive: {
    color: palette.white,
  },
  adminShell: {
    flex: 1,
    width: '100%',
    flexDirection: 'row-reverse',
    backgroundColor: '#F2F3F1',
  },
  adminShellCompact: {
    flexDirection: 'column',
  },
  adminSidebar: {
    width: 238,
    backgroundColor: palette.greenDark,
    paddingVertical: 26,
    paddingHorizontal: 16,
  },
  adminLogo: {
    color: palette.white,
    fontSize: 26,
    fontWeight: '900',
    textAlign: 'center',
    marginBottom: 28,
  },
  sidebarItem: {
    height: 42,
    borderRadius: 8,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    paddingHorizontal: 12,
    gap: 10,
    marginBottom: 8,
  },
  sidebarItemActive: {
    backgroundColor: '#FFFFFF24',
  },
  sidebarText: {
    color: palette.white,
    fontSize: 13,
    fontWeight: '700',
  },
  supportLine: {
    marginTop: 'auto',
    borderTopWidth: 1,
    borderTopColor: '#FFFFFF24',
    paddingTop: 18,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 10,
  },
  adminChipNav: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row-reverse',
    gap: 8,
    backgroundColor: palette.white,
  },
  adminChip: {
    height: 34,
    borderRadius: 18,
    paddingHorizontal: 12,
    backgroundColor: '#EDF1F0',
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
  },
  adminChipActive: {
    backgroundColor: palette.green,
  },
  adminChipText: {
    fontSize: 12,
    color: palette.greenDark,
    fontWeight: '800',
  },
  adminChipTextActive: {
    color: palette.white,
  },
  adminMain: {
    flex: 1,
  },
  adminTopBar: {
    height: 74,
    paddingHorizontal: 24,
    backgroundColor: palette.white,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 16,
  },
  adminTopBarCompact: {
    paddingHorizontal: 12,
    gap: 8,
  },
  adminUser: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 10,
  },
  adminAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: '#C8D2D6',
  },
  adminUserName: {
    fontSize: 13,
    fontWeight: '900',
  },
  adminSearch: {
    flex: 1,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#F2F4F4',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 14,
    gap: 8,
  },
  adminSearchInput: {
    flex: 1,
    color: palette.ink,
    writingDirection: 'rtl',
    fontSize: 13,
  },
  adminNotify: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.greenSoft,
  },
  adminContent: {
    padding: 24,
    paddingBottom: 40,
  },
  statsGrid: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: 14,
  },
  statCard: {
    flexGrow: 1,
    flexBasis: 180,
    minHeight: 108,
    borderRadius: 8,
    padding: 16,
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: palette.border,
  },
  statIcon: {
    width: 38,
    height: 38,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'flex-end',
  },
  statValue: {
    marginTop: 8,
    fontSize: 22,
    fontWeight: '900',
  },
  statLabel: {
    marginTop: 2,
    color: palette.muted,
    fontSize: 12,
  },
  statDelta: {
    position: 'absolute',
    left: 16,
    bottom: 16,
    fontWeight: '900',
    fontSize: 13,
  },
  adminCardsRow: {
    marginTop: 18,
    flexDirection: 'row-reverse',
    gap: 14,
  },
  adminCardsColumn: {
    flexDirection: 'column',
  },
  ordersMini: {
    flex: 1,
    minWidth: 260,
    borderRadius: 8,
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 16,
  },
  miniOrder: {
    marginTop: 12,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 10,
  },
  miniOrderImg: {
    width: 44,
    height: 44,
    borderRadius: 8,
    resizeMode: 'cover',
  },
  chartCard: {
    flex: 1.5,
    minWidth: 300,
    borderRadius: 8,
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 16,
  },
  cardHeader: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  adminCardTitle: {
    fontSize: 15,
    fontWeight: '900',
  },
  adminCardValue: {
    color: palette.green,
    fontWeight: '900',
  },
  chartArea: {
    height: 150,
    marginTop: 14,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
  },
  chartColumn: {
    width: 22,
    alignItems: 'center',
    justifyContent: 'flex-end',
    flexDirection: 'row',
    gap: 3,
  },
  chartBar: {
    width: 8,
    borderRadius: 4,
    backgroundColor: palette.green,
  },
  chartBarSoft: {
    width: 8,
    borderRadius: 4,
    backgroundColor: '#BFE9DF',
  },
  performanceCard: {
    width: 240,
    borderRadius: 8,
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 16,
    alignItems: 'center',
  },
  donutWrap: {
    marginTop: 12,
    alignItems: 'center',
  },
  donutOuter: {
    width: 92,
    height: 92,
    borderRadius: 46,
    borderWidth: 12,
    borderColor: palette.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  donutInner: {
    width: 58,
    height: 58,
    borderRadius: 29,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: palette.white,
  },
  donutPercent: {
    color: palette.green,
    fontWeight: '900',
  },
  secondaryButton: {
    marginTop: 12,
    height: 34,
    paddingHorizontal: 14,
    borderRadius: 17,
    borderWidth: 1,
    borderColor: palette.border,
    justifyContent: 'center',
  },
  secondaryButtonText: {
    color: palette.green,
    fontSize: 12,
    fontWeight: '800',
    textAlign: 'center',
  },
  adminSectionTitle: {
    marginTop: 24,
    marginBottom: 12,
    fontSize: 17,
    fontWeight: '900',
  },
  adminProductGrid: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: 14,
  },
  adminProductCard: {
    flexBasis: 170,
    flexGrow: 1,
    maxWidth: 230,
    borderRadius: 8,
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: palette.border,
    overflow: 'hidden',
  },
  adminProductImage: {
    height: 120,
    width: '100%',
    resizeMode: 'cover',
  },
  adminProductMeta: {
    padding: 10,
    alignItems: 'flex-end',
  },
  adminProductTitle: {
    fontSize: 13,
    fontWeight: '900',
  },
  tableCard: {
    marginTop: 18,
    borderRadius: 8,
    backgroundColor: palette.white,
    borderWidth: 1,
    borderColor: palette.border,
    padding: 16,
  },
  tableTools: {
    flexDirection: 'row-reverse',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 14,
  },
  adminPrimary: {
    height: 36,
    borderRadius: 18,
    paddingHorizontal: 14,
    backgroundColor: palette.green,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
  },
  adminPrimaryText: {
    color: palette.white,
    fontWeight: '900',
    fontSize: 12,
  },
  filterButton: {
    height: 36,
    borderRadius: 18,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: palette.border,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 6,
  },
  filterText: {
    color: palette.muted,
    fontSize: 12,
    fontWeight: '800',
  },
  table: {
    minWidth: 760,
  },
  tableHeader: {
    height: 42,
    borderRadius: 8,
    backgroundColor: '#F4F6F6',
    flexDirection: 'row-reverse',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  tableHeaderText: {
    flex: 1,
    color: palette.muted,
    fontSize: 12,
    fontWeight: '900',
  },
  tableRow: {
    minHeight: 62,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
  },
  tableEntity: {
    flex: 1,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
  },
  tableThumb: {
    width: 36,
    height: 36,
    borderRadius: 8,
    resizeMode: 'cover',
  },
  tableName: {
    fontSize: 12,
    color: palette.ink,
  },
});
