import { StyleSheet } from 'react-native';

export const palette = {
  green: '#179B7D',
  greenDark: '#075247',
  greenMid: '#2E6F61',
  greenSoft: '#DFF8EF',
  bg: '#F7F7F3',
  card: '#FFFFFF',
  ink: '#151A1E',
  muted: '#7C8289',
  border: '#E4E8E8',
  line: '#F0F1EF',
  amber: '#F7B531',
  amberSoft: '#FFF4D9',
  red: '#D83B42',
  redSoft: '#FDE4E5',
  purple: '#4F24A6',
  purpleSoft: '#ECE7FA',
  blue: '#245AA6',
  graySoft: '#F3F4F2',
  white: '#FFFFFF',
};

export const toneStyles = {
  green: { text: { color: palette.green }, soft: { backgroundColor: palette.greenSoft } },
  amber: { text: { color: '#E58D18' }, soft: { backgroundColor: palette.amberSoft } },
  red: { text: { color: palette.red }, soft: { backgroundColor: palette.redSoft } },
  purple: { text: { color: palette.purple }, soft: { backgroundColor: palette.purpleSoft } },
};

export const styles = StyleSheet.create({
  shell: {
    flex: 1,
    minHeight: 0,
    flexDirection: 'row-reverse',
    backgroundColor: palette.bg,
  },
  shellCompact: {
    flexDirection: 'column',
  },
  sidebar: {
    width: 190,
    minWidth: 190,
    maxWidth: 190,
    flexBasis: 190,
    flexGrow: 0,
    flexShrink: 0,
    backgroundColor: palette.greenDark,
  },
  sidebarContent: {
    flexGrow: 1,
    paddingTop: 20,
    paddingHorizontal: 10,
    paddingBottom: 14,
  },
  logoBlock: {
    alignItems: 'center',
    marginBottom: 18,
  },
  navList: {
    gap: 5,
  },
  navItem: {
    minHeight: 39,
    borderRadius: 8,
    paddingHorizontal: 9,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
  },
  navItemActive: {
    backgroundColor: '#FFFFFF24',
  },
  navText: {
    color: '#DDF4EE',
    textAlign: 'right',
    fontSize: 13,
    fontWeight: '600',
  },
  navTextActive: {
    color: '#FFFFFF',
    fontWeight: '900',
  },
  supportLine: {
    height: 1,
    marginTop: 'auto',
    marginBottom: 26,
    backgroundColor: '#FFFFFF44',
  },
  supportItem: {
    minHeight: 42,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
  },
  main: {
    flex: 1,
    minWidth: 0,
  },
  topbar: {
    minHeight: 82,
    margin: 20,
    marginBottom: 18,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.card,
    paddingHorizontal: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 22,
    shadowColor: '#0A1F17',
    shadowOpacity: 0.06,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 6 },
  },
  userBox: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 14,
  },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: 26,
    backgroundColor: '#D8D8D8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarText: {
    color: palette.greenDark,
    fontSize: 20,
    fontWeight: '900',
  },
  userName: {
    color: palette.ink,
    textAlign: 'right',
    fontSize: 17,
    fontWeight: '900',
  },
  userRole: {
    color: palette.green,
    textAlign: 'right',
    fontSize: 14,
    fontWeight: '800',
    marginTop: 4,
  },
  bellButton: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: palette.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  searchBox: {
    width: '34%',
    minWidth: 270,
    height: 52,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: '#F7F7F7',
    flexDirection: 'row-reverse',
    alignItems: 'center',
    paddingHorizontal: 18,
    gap: 12,
  },
  searchInput: {
    flex: 1,
    color: palette.ink,
    fontSize: 16,
    writingDirection: 'rtl',
  },
  contentScroll: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 20,
    paddingBottom: 32,
    gap: 18,
  },
  errorBox: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#F3D19A',
    backgroundColor: '#FFF5E8',
    padding: 15,
  },
  errorText: {
    color: '#9A5B00',
    textAlign: 'right',
    fontSize: 14,
    fontWeight: '800',
  },
  noticeBox: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#A9DECf',
    backgroundColor: palette.greenSoft,
    padding: 14,
  },
  noticeText: {
    color: palette.greenDark,
    textAlign: 'right',
    fontSize: 14,
    fontWeight: '800',
  },
  emptyState: {
    minHeight: 92,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 18,
    alignSelf: 'stretch',
  },
  emptyText: {
    color: palette.muted,
    fontSize: 15,
    fontWeight: '800',
    textAlign: 'center',
  },
  statsGrid: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: 14,
  },
  statCard: {
    flexGrow: 1,
    flexBasis: 200,
    minHeight: 118,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.card,
    padding: 20,
    shadowColor: '#0A1F17',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  statIcon: {
    position: 'absolute',
    right: 18,
    top: 36,
    width: 54,
    height: 54,
    borderRadius: 27,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statLabel: {
    color: palette.ink,
    textAlign: 'left',
    fontSize: 16,
    fontWeight: '700',
  },
  statValue: {
    marginTop: 8,
    color: '#000000',
    textAlign: 'left',
    writingDirection: 'ltr',
    fontSize: 24,
    fontWeight: '900',
  },
  statFooter: {
    marginTop: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  statDelta: {
    fontSize: 22,
    fontWeight: '900',
  },
  statHint: {
    color: palette.muted,
    fontSize: 14,
  },
  overviewGrid: {
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 22,
  },
  latestOrdersCard: {
    flex: 1.1,
    minWidth: 330,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.card,
    padding: 20,
  },
  panelHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 16,
    gap: 12,
  },
  panelTitle: {
    color: palette.ink,
    textAlign: 'right',
    fontSize: 18,
    fontWeight: '900',
  },
  panelNumber: {
    marginTop: 10,
    color: palette.ink,
    textAlign: 'right',
    fontSize: 17,
    fontWeight: '900',
  },
  linkText: {
    color: palette.green,
    fontSize: 15,
    fontWeight: '900',
  },
  miniOrderRow: {
    minHeight: 70,
    borderBottomWidth: 1,
    borderBottomColor: palette.line,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 18,
  },
  orderCustomer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  entityName: {
    color: palette.ink,
    textAlign: 'right',
    fontSize: 15,
    fontWeight: '900',
  },
  mutedSmall: {
    color: palette.muted,
    textAlign: 'right',
    fontSize: 12,
    marginTop: 3,
  },
  moneySmall: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: '900',
  },
  statusPill: {
    minWidth: 92,
    borderRadius: 22,
    paddingHorizontal: 15,
    paddingVertical: 8,
    alignItems: 'center',
  },
  statusText: {
    fontSize: 14,
    fontWeight: '800',
  },
  productThumb: {
    resizeMode: 'cover',
  },
  productThumbPlaceholder: {
    backgroundColor: palette.greenSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  smallFilter: {
    minWidth: 138,
    height: 44,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#CCD5D2',
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  smallFilterText: {
    color: palette.green,
    fontSize: 15,
    fontWeight: '800',
  },
  starsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  outlineButton: {
    marginTop: 20,
    height: 44,
    alignSelf: 'stretch',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: palette.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  outlineButtonText: {
    color: palette.green,
    fontSize: 15,
    fontWeight: '800',
  },
  bestProducts: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.card,
    padding: 20,
  },
  bestProductsList: {
    flexDirection: 'row-reverse',
    gap: 24,
    paddingVertical: 2,
  },
  bestProductCard: {
    width: 218,
    height: 126,
    borderRadius: 16,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: palette.line,
    flexDirection: 'row-reverse',
    overflow: 'hidden',
  },
  bestProductImage: {
    width: 96,
    height: '100%',
    resizeMode: 'cover',
  },
  bestProductInfo: {
    flex: 1,
    padding: 12,
    alignItems: 'flex-end',
  },
  bestProductName: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: '900',
  },
  salesText: {
    marginTop: 10,
    color: palette.green,
    fontSize: 13,
    fontWeight: '900',
  },
  priceText: {
    marginTop: 7,
    color: palette.ink,
    fontSize: 12,
  },
  tabsBar: {
    minHeight: 54,
    borderRadius: 14,
    backgroundColor: palette.card,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'flex-end',
    padding: 6,
    gap: 10,
    shadowColor: '#0A1F17',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  tabButton: {
    minWidth: 122,
    minHeight: 42,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  tabButtonActive: {
    backgroundColor: palette.green,
  },
  tabButtonText: {
    color: palette.ink,
    fontSize: 16,
    fontWeight: '700',
  },
  tabButtonTextActive: {
    color: '#FFFFFF',
  },
  filterRow: {
    minHeight: 64,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
  },
  primaryButton: {
    width: 220,
    minHeight: 52,
    borderRadius: 14,
    backgroundColor: palette.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontWeight: '800',
  },
  filterButton: {
    minWidth: 220,
    minHeight: 52,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#CCD5D2',
    backgroundColor: palette.card,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  filterText: {
    color: palette.greenMid,
    fontSize: 18,
    fontWeight: '800',
  },
  tableCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.card,
    overflow: 'hidden',
  },
  tableHeader: {
    minHeight: 54,
    backgroundColor: '#F3F3F3',
    flexDirection: 'row-reverse',
    alignItems: 'center',
    paddingHorizontal: 22,
    gap: 18,
  },
  tableHeaderText: {
    flex: 1,
    color: palette.ink,
    textAlign: 'right',
    fontSize: 14,
    fontWeight: '800',
  },
  orderRow: {
    minHeight: 92,
    borderBottomWidth: 1,
    borderBottomColor: palette.line,
    paddingHorizontal: 22,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 18,
  },
  productRow: {
    minHeight: 86,
    borderBottomWidth: 1,
    borderBottomColor: palette.line,
    paddingHorizontal: 22,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 18,
  },
  categoryRow: {
    minHeight: 76,
    borderBottomWidth: 1,
    borderBottomColor: palette.line,
    paddingHorizontal: 22,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 18,
  },
  storeRow: {
    minHeight: 94,
    borderBottomWidth: 1,
    borderBottomColor: palette.line,
    paddingHorizontal: 22,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 16,
  },
  storeActions: {
    flex: 1.2,
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 7,
  },
  smallActionButton: {
    minHeight: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.green,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  smallActionText: {
    color: palette.greenDark,
    fontSize: 12,
    fontWeight: '800',
  },
  packageGrid: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: 12,
  },
  packageCard: {
    flexGrow: 1,
    flexBasis: 220,
    minHeight: 112,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.border,
    borderTopWidth: 4,
    borderTopColor: palette.green,
    backgroundColor: palette.card,
    padding: 16,
  },
  packageName: {
    color: palette.ink,
    textAlign: 'right',
    fontSize: 17,
    fontWeight: '900',
  },
  packagePrice: {
    marginTop: 7,
    color: palette.green,
    textAlign: 'right',
    fontSize: 14,
    fontWeight: '800',
  },
  packageLimits: {
    marginTop: 9,
    color: palette.muted,
    textAlign: 'right',
    fontSize: 13,
  },
  packageManagementGrid: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: 16,
  },
  packageManageCard: {
    flexGrow: 1,
    flexBasis: 300,
    maxWidth: 430,
    minHeight: 290,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.border,
    borderTopWidth: 4,
    borderTopColor: palette.green,
    backgroundColor: palette.card,
    padding: 20,
  },
  packageDisabledCard: {
    opacity: 0.68,
    borderTopColor: palette.muted,
  },
  packageManageHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 14,
  },
  packageManageTitle: {
    flex: 1,
    alignItems: 'flex-end',
    gap: 10,
  },
  packageManagePrice: {
    marginTop: 18,
    color: palette.greenDark,
    textAlign: 'right',
    fontSize: 24,
    fontWeight: '900',
  },
  packageDuration: {
    marginTop: 5,
    color: palette.muted,
    textAlign: 'right',
    fontSize: 13,
  },
  packageLimitsGrid: {
    marginTop: 18,
    flexDirection: 'row-reverse',
    gap: 8,
  },
  packageLimitItem: {
    flex: 1,
    minHeight: 66,
    borderRadius: 8,
    backgroundColor: palette.graySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  packageLimitValue: {
    color: palette.ink,
    fontSize: 18,
    fontWeight: '900',
  },
  packageLimitLabel: {
    marginTop: 3,
    color: palette.muted,
    fontSize: 12,
  },
  packageEditButton: {
    marginTop: 18,
    minHeight: 42,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.green,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  packageEditText: {
    color: palette.greenDark,
    fontSize: 14,
    fontWeight: '800',
  },
  tableCell: {
    flex: 1,
    color: palette.ink,
    textAlign: 'center',
    fontSize: 14,
    fontWeight: '700',
  },
  productEntity: {
    flex: 1.25,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 12,
  },
  rowActionsWide: {
    width: 170,
    gap: 10,
  },
  acceptButton: {
    height: 38,
    borderRadius: 19,
    backgroundColor: palette.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  acceptText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '800',
  },
  rejectButton: {
    height: 38,
    borderRadius: 19,
    backgroundColor: '#F5F5F5',
    borderWidth: 1,
    borderColor: palette.line,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rejectText: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: '700',
  },
  thumbnailStack: {
    width: 94,
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconActions: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 22,
  },
  iconButton: {
    width: 38,
    height: 38,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.redSoft,
    backgroundColor: '#FFFFFF',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reelsGrid: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: 30,
  },
  reelCard: {
    width: 220,
    height: 260,
    borderRadius: 18,
    backgroundColor: palette.card,
    overflow: 'hidden',
    shadowColor: '#0A1F17',
    shadowOpacity: 0.07,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
  },
  reelImage: {
    width: '100%',
    height: 185,
    resizeMode: 'cover',
  },
  reelStatus: {
    position: 'absolute',
    right: 12,
    top: 152,
    minWidth: 70,
    borderRadius: 16,
    backgroundColor: palette.greenSoft,
    paddingVertical: 6,
    alignItems: 'center',
  },
  reelStatusText: {
    color: palette.greenDark,
    fontSize: 12,
    fontWeight: '800',
  },
  reelDuration: {
    position: 'absolute',
    left: 12,
    top: 152,
    borderRadius: 14,
    backgroundColor: '#00000066',
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  reelDurationText: {
    color: '#FFFFFF',
    fontSize: 11,
  },
  reelMeta: {
    padding: 12,
    gap: 8,
  },
  reelTitle: {
    color: palette.ink,
    textAlign: 'right',
    fontSize: 14,
    fontWeight: '800',
  },
  reelViews: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
  },
  dotsButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#FFFFFFAA',
  },
  dotsText: {
    color: '#66717C',
    fontSize: 24,
    lineHeight: 24,
    fontWeight: '900',
  },
  switchTrack: {
    width: 58,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#D8D8D8',
    padding: 3,
    justifyContent: 'center',
  },
  switchTrackActive: {
    backgroundColor: palette.green,
  },
  switchDot: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
  },
  switchDotActive: {
    alignSelf: 'flex-end',
  },
  modalBackdrop: {
    flex: 1,
    backgroundColor: '#071B1788',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  modalCard: {
    width: '100%',
    maxWidth: 680,
    maxHeight: '92%',
    borderRadius: 8,
    backgroundColor: palette.card,
    overflow: 'hidden',
    shadowColor: '#000000',
    shadowOpacity: 0.2,
    shadowRadius: 24,
    shadowOffset: { width: 0, height: 10 },
  },
  modalHeader: {
    minHeight: 68,
    paddingHorizontal: 22,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalTitle: {
    color: palette.ink,
    fontSize: 20,
    fontWeight: '900',
    textAlign: 'right',
  },
  modalClose: {
    width: 40,
    height: 40,
    borderRadius: 8,
    backgroundColor: palette.graySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalScroll: {
    flexShrink: 1,
  },
  modalBody: {
    padding: 22,
    gap: 17,
  },
  formField: {
    flex: 1,
    minWidth: 0,
    gap: 8,
  },
  formLabel: {
    color: palette.ink,
    fontSize: 14,
    fontWeight: '800',
    textAlign: 'right',
  },
  formSectionTitle: {
    color: palette.greenDark,
    fontSize: 16,
    fontWeight: '900',
    textAlign: 'right',
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
  },
  formInput: {
    minHeight: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#CBD4D1',
    backgroundColor: '#FFFFFF',
    color: palette.ink,
    fontSize: 15,
    paddingHorizontal: 14,
    writingDirection: 'rtl',
  },
  uploadRow: {
    minHeight: 58,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 12,
  },
  uploadButton: {
    flex: 1,
    minHeight: 48,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#CBD4D1',
    backgroundColor: '#FFFFFF',
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingHorizontal: 14,
  },
  uploadButtonText: {
    color: palette.greenDark,
    fontSize: 14,
    fontWeight: '900',
    textAlign: 'center',
  },
  uploadValue: {
    color: palette.muted,
    fontSize: 12,
    textAlign: 'right',
    writingDirection: 'ltr',
  },
  formTextArea: {
    minHeight: 92,
    paddingTop: 13,
    textAlignVertical: 'top',
  },
  formColumns: {
    flexDirection: 'row-reverse',
    gap: 14,
  },
  choiceRow: {
    flexDirection: 'row-reverse',
    flexWrap: 'wrap',
    gap: 8,
  },
  choiceButton: {
    minHeight: 40,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#CBD4D1',
    paddingHorizontal: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  choiceButtonActive: {
    borderColor: palette.green,
    backgroundColor: palette.greenSoft,
  },
  choiceText: {
    color: palette.greenMid,
    fontSize: 14,
    fontWeight: '700',
  },
  choiceTextActive: {
    color: palette.greenDark,
    fontWeight: '900',
  },
  formError: {
    borderRadius: 8,
    backgroundColor: palette.redSoft,
    color: palette.red,
    padding: 12,
    textAlign: 'right',
    fontSize: 14,
    fontWeight: '800',
  },
  modalFooter: {
    minHeight: 72,
    borderTopWidth: 1,
    borderTopColor: palette.border,
    paddingHorizontal: 22,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  saveButton: {
    minWidth: 130,
    minHeight: 46,
    borderRadius: 8,
    backgroundColor: palette.green,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  saveButtonText: {
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '900',
  },
  cancelButton: {
    minWidth: 100,
    minHeight: 46,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#CBD4D1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButtonText: {
    color: palette.ink,
    fontSize: 15,
    fontWeight: '800',
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  grayAvatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#D2D2D2',
  },
  grayAvatarSmall: {
    width: 42,
    height: 42,
    borderRadius: 21,
    backgroundColor: '#D2D2D2',
  },
  tableHorizontalScroll: {
    alignSelf: 'stretch',
  },
  customerTable: {
    minWidth: 980,
  },
  customerRow: {
    minHeight: 86,
    borderBottomWidth: 1,
    borderBottomColor: palette.line,
    paddingHorizontal: 22,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 18,
  },
  customerEntity: {
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 10,
  },
  customerNameColumn: { width: 230, flex: 0 },
  customerRoleColumn: { width: 170, flex: 0 },
  customerPhoneColumn: { width: 170, flex: 0 },
  customerStatusColumn: { width: 140, flex: 0, alignItems: 'center' },
  customerActionColumn: { width: 130, flex: 0, alignItems: 'center' },
  reviewTable: {
    minWidth: 1180,
  },
  reviewProductColumn: { width: 210, flex: 0 },
  reviewUserColumn: { width: 190, flex: 0 },
  reviewDateColumn: { width: 130, flex: 0 },
  reviewRatingColumn: { width: 130, flex: 0 },
  reviewCommentColumn: { width: 250, flex: 0 },
  reviewActionColumn: { width: 130, flex: 0 },
  reviewRow: {
    minHeight: 118,
    borderBottomWidth: 1,
    borderBottomColor: palette.line,
    paddingHorizontal: 22,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 18,
  },
  reviewActions: {
    flex: 1,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  reviewApproveButton: {
    width: 36,
    height: 36,
    borderRadius: 8,
    backgroundColor: palette.green,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewRejectButton: {
    width: 36,
    height: 36,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.red,
    backgroundColor: palette.redSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewComment: {
    color: palette.ink,
    textAlign: 'right',
    fontSize: 16,
  },
  starsText: {
    color: palette.amber,
    fontSize: 20,
    textAlign: 'center',
  },
  packageActiveRow: {
    minHeight: 64,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 18,
  },
  paymentsTables: {
    flexDirection: 'row',
    gap: 22,
  },
  paymentTable: {
    flex: 1,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.card,
    padding: 20,
  },
  paymentRow: {
    minHeight: 68,
    borderBottomWidth: 1,
    borderBottomColor: palette.line,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 14,
  },
  settingsEmpty: {
    minHeight: 360,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.border,
    backgroundColor: palette.card,
    padding: 32,
    alignItems: 'flex-end',
  },
  mutedText: {
    marginTop: 12,
    color: palette.muted,
    textAlign: 'right',
    fontSize: 16,
  },
  mobileNav: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    gap: 10,
    backgroundColor: palette.card,
  },
  mobileNavItem: {
    minHeight: 38,
    borderRadius: 10,
    paddingHorizontal: 12,
    backgroundColor: palette.greenSoft,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    gap: 8,
  },
  mobileNavActive: {
    backgroundColor: palette.green,
  },
  mobileNavText: {
    color: palette.green,
    fontSize: 12,
    fontWeight: '800',
  },
  mobileNavTextActive: {
    color: '#FFFFFF',
  },
});
